package model

// Code generated by graphqlgen. DO NOT EDIT.

import (
	"time"
)

// Custom scalar for UUID values
type UUID string

// Custom scalar for Time values
type Time time.Time

// Custom scalar for JSON objects
type JSON map[string]any

type OrderDirection string

const (
	OrderDirectionASC  OrderDirection = "ASC"
	OrderDirectionDESC OrderDirection = "DESC"
)

type FilterOperator string

const (
	FilterOperatorEQ     FilterOperator = "EQ"
	FilterOperatorNE     FilterOperator = "NE"
	FilterOperatorGT     FilterOperator = "GT"
	FilterOperatorLT     FilterOperator = "LT"
	FilterOperatorGTE    FilterOperator = "GTE"
	FilterOperatorLTE    FilterOperator = "LTE"
	FilterOperatorILIKE  FilterOperator = "ILIKE"
	FilterOperatorLIKE   FilterOperator = "LIKE"
	FilterOperatorIN     FilterOperator = "IN"
	FilterOperatorNOT_IN FilterOperator = "NOT_IN"
)

// Author with profile, books, and tags
type Author struct {
	Id          string           `json:"id,omitempty"`
	CreatedAt   *time.Time       `json:"created_at,omitempty"`
	UpdatedAt   *time.Time       `json:"updated_at,omitempty"`
	Active      bool             `json:"active,omitempty"`
	Books       []*Book          `json:"books,omitempty"`
	Email       string           `json:"email,omitempty"`
	FullName    string           `json:"full_name,omitempty"`
	HiredAt     *time.Time       `json:"hired_at,omitempty"`
	PenName     string           `json:"pen_name,omitempty"`
	Profile     *AuthorProfile   `json:"profile,omitempty"`
	Publisher   *PublishingHouse `json:"publisher,omitempty"`
	PublisherId string           `json:"publisher_id,omitempty"`
	Tags        []*Tag           `json:"tags,omitempty"`
}

// Author profile details
type AuthorProfile struct {
	Id            string  `json:"id,omitempty"`
	Author        *Author `json:"author,omitempty"`
	AuthorId      string  `json:"author_id,omitempty"`
	Biography     string  `json:"biography,omitempty"`
	FavoriteGenre string  `json:"favorite_genre,omitempty"`
	WritingStyle  string  `json:"writing_style,omitempty"`
}

// Book with author, publisher, chapters, and tags
type Book struct {
	Id            string           `json:"id,omitempty"`
	CreatedAt     *time.Time       `json:"created_at,omitempty"`
	UpdatedAt     *time.Time       `json:"updated_at,omitempty"`
	Author        *Author          `json:"author,omitempty"`
	AuthorId      string           `json:"author_id,omitempty"`
	Chapters      []*Chapter       `json:"chapters,omitempty"`
	Isbn          string           `json:"isbn,omitempty"`
	LastReprintAt *time.Time       `json:"last_reprint_at,omitempty"`
	Publisher     *PublishingHouse `json:"publisher,omitempty"`
	PublisherId   string           `json:"publisher_id,omitempty"`
	ReleaseDate   *time.Time       `json:"release_date,omitempty"`
	Status        string           `json:"status,omitempty"`
	Tags          []*Tag           `json:"tags,omitempty"`
	Title         string           `json:"title,omitempty"`
}

// Chapter belonging to a book
type Chapter struct {
	Id           string `json:"id,omitempty"`
	Book         *Book  `json:"book,omitempty"`
	BookId       string `json:"book_id,omitempty"`
	ChapterIndex int    `json:"chapter_index,omitempty"`
	Title        string `json:"title,omitempty"`
	WordCount    int    `json:"word_count,omitempty"`
}

// Headquarters belongs to a publishing house
type Headquarters struct {
	Id           string           `json:"id,omitempty"`
	AddressLine1 string           `json:"address_line1,omitempty"`
	AddressLine2 string           `json:"address_line2,omitempty"`
	City         string           `json:"city,omitempty"`
	Country      string           `json:"country,omitempty"`
	OpenedAt     *time.Time       `json:"opened_at,omitempty"`
	Publisher    *PublishingHouse `json:"publisher,omitempty"`
	PublisherId  string           `json:"publisher_id,omitempty"`
}

type PageInfo struct {
	Total           int  `json:"total,omitempty"`
	HasNextPage     bool `json:"hasNextPage,omitempty"`
	HasPreviousPage bool `json:"hasPreviousPage,omitempty"`
}

// Publishing house with catalog and authors
type PublishingHouse struct {
	Id            string        `json:"id,omitempty"`
	CreatedAt     *time.Time    `json:"created_at,omitempty"`
	UpdatedAt     *time.Time    `json:"updated_at,omitempty"`
	Authors       []*Author     `json:"authors,omitempty"`
	Books         []*Book       `json:"books,omitempty"`
	EstablishedAt *time.Time    `json:"established_at,omitempty"`
	Headquarters  *Headquarters `json:"headquarters,omitempty"`
	ImprintPrefix string        `json:"imprint_prefix,omitempty"`
	Name          string        `json:"name,omitempty"`
}

// Tag used for books and authors
type Tag struct {
	Id          string     `json:"id,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Authors     []*Author  `json:"authors,omitempty"`
	Books       []*Book    `json:"books,omitempty"`
	Category    string     `json:"category,omitempty"`
	Description string     `json:"description,omitempty"`
	Name        string     `json:"name,omitempty"`
}

// Input type for pagination parameters
type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

// Input type for ordering parameters
type OrderByInput struct {
	Field     string          `json:"field,omitempty"`
	Direction *OrderDirection `json:"direction,omitempty"`
}

// Input type for filtering
type FilterInput struct {
	Field    string         `json:"field,omitempty"`
	Operator FilterOperator `json:"operator,omitempty"`
	Value    string         `json:"value,omitempty"`
}

// Create payload for Author
type CreateAuthorInput struct {
	Active      bool             `json:"active,omitempty"`
	Email       string           `json:"email,omitempty"`
	FullName    string           `json:"fullName,omitempty"`
	PublisherId string           `json:"publisherId,omitempty"`
	Books       []*Book          `json:"books,omitempty"`
	CreatedAt   *time.Time       `json:"createdAt,omitempty"`
	HiredAt     *time.Time       `json:"hiredAt,omitempty"`
	PenName     *string          `json:"penName,omitempty"`
	Profile     *AuthorProfile   `json:"profile,omitempty"`
	Publisher   *PublishingHouse `json:"publisher,omitempty"`
	Tags        []*Tag           `json:"tags,omitempty"`
	UpdatedAt   *time.Time       `json:"updatedAt,omitempty"`
}

// Update payload for Author
type UpdateAuthorInput struct {
	Active      *bool            `json:"active,omitempty"`
	Email       *string          `json:"email,omitempty"`
	FullName    *string          `json:"fullName,omitempty"`
	PublisherId *string          `json:"publisherId,omitempty"`
	Books       []*Book          `json:"books,omitempty"`
	CreatedAt   *time.Time       `json:"createdAt,omitempty"`
	HiredAt     *time.Time       `json:"hiredAt,omitempty"`
	PenName     *string          `json:"penName,omitempty"`
	Profile     *AuthorProfile   `json:"profile,omitempty"`
	Publisher   *PublishingHouse `json:"publisher,omitempty"`
	Tags        []*Tag           `json:"tags,omitempty"`
	UpdatedAt   *time.Time       `json:"updatedAt,omitempty"`
}

// Create payload for AuthorProfile
type CreateAuthorProfileInput struct {
	AuthorId      string  `json:"authorId,omitempty"`
	Author        *Author `json:"author,omitempty"`
	Biography     *string `json:"biography,omitempty"`
	FavoriteGenre *string `json:"favoriteGenre,omitempty"`
	WritingStyle  *string `json:"writingStyle,omitempty"`
}

// Update payload for AuthorProfile
type UpdateAuthorProfileInput struct {
	AuthorId      *string `json:"authorId,omitempty"`
	Author        *Author `json:"author,omitempty"`
	Biography     *string `json:"biography,omitempty"`
	FavoriteGenre *string `json:"favoriteGenre,omitempty"`
	WritingStyle  *string `json:"writingStyle,omitempty"`
}

// Create payload for Book
type CreateBookInput struct {
	AuthorId      string           `json:"authorId,omitempty"`
	Isbn          string           `json:"isbn,omitempty"`
	PublisherId   string           `json:"publisherId,omitempty"`
	Status        string           `json:"status,omitempty"`
	Title         string           `json:"title,omitempty"`
	Author        *Author          `json:"author,omitempty"`
	Chapters      []*Chapter       `json:"chapters,omitempty"`
	CreatedAt     *time.Time       `json:"createdAt,omitempty"`
	LastReprintAt *time.Time       `json:"lastReprintAt,omitempty"`
	Publisher     *PublishingHouse `json:"publisher,omitempty"`
	ReleaseDate   *time.Time       `json:"releaseDate,omitempty"`
	Tags          []*Tag           `json:"tags,omitempty"`
	UpdatedAt     *time.Time       `json:"updatedAt,omitempty"`
}

// Update payload for Book
type UpdateBookInput struct {
	AuthorId      *string          `json:"authorId,omitempty"`
	Isbn          *string          `json:"isbn,omitempty"`
	PublisherId   *string          `json:"publisherId,omitempty"`
	Status        *string          `json:"status,omitempty"`
	Title         *string          `json:"title,omitempty"`
	Author        *Author          `json:"author,omitempty"`
	Chapters      []*Chapter       `json:"chapters,omitempty"`
	CreatedAt     *time.Time       `json:"createdAt,omitempty"`
	LastReprintAt *time.Time       `json:"lastReprintAt,omitempty"`
	Publisher     *PublishingHouse `json:"publisher,omitempty"`
	ReleaseDate   *time.Time       `json:"releaseDate,omitempty"`
	Tags          []*Tag           `json:"tags,omitempty"`
	UpdatedAt     *time.Time       `json:"updatedAt,omitempty"`
}

// Create payload for Chapter
type CreateChapterInput struct {
	BookId       string `json:"bookId,omitempty"`
	ChapterIndex int    `json:"chapterIndex,omitempty"`
	Title        string `json:"title,omitempty"`
	WordCount    int    `json:"wordCount,omitempty"`
	Book         *Book  `json:"book,omitempty"`
}

// Update payload for Chapter
type UpdateChapterInput struct {
	BookId       *string `json:"bookId,omitempty"`
	ChapterIndex *int    `json:"chapterIndex,omitempty"`
	Title        *string `json:"title,omitempty"`
	WordCount    *int    `json:"wordCount,omitempty"`
	Book         *Book   `json:"book,omitempty"`
}

// Create payload for Headquarters
type CreateHeadquartersInput struct {
	AddressLine1 string           `json:"addressLine1,omitempty"`
	City         string           `json:"city,omitempty"`
	Country      string           `json:"country,omitempty"`
	PublisherId  string           `json:"publisherId,omitempty"`
	AddressLine2 *string          `json:"addressLine2,omitempty"`
	OpenedAt     *time.Time       `json:"openedAt,omitempty"`
	Publisher    *PublishingHouse `json:"publisher,omitempty"`
}

// Update payload for Headquarters
type UpdateHeadquartersInput struct {
	AddressLine1 *string          `json:"addressLine1,omitempty"`
	City         *string          `json:"city,omitempty"`
	Country      *string          `json:"country,omitempty"`
	PublisherId  *string          `json:"publisherId,omitempty"`
	AddressLine2 *string          `json:"addressLine2,omitempty"`
	OpenedAt     *time.Time       `json:"openedAt,omitempty"`
	Publisher    *PublishingHouse `json:"publisher,omitempty"`
}

// Create payload for PublishingHouse
type CreatePublishingHouseInput struct {
	Name          string        `json:"name,omitempty"`
	Authors       []*Author     `json:"authors,omitempty"`
	Books         []*Book       `json:"books,omitempty"`
	CreatedAt     *time.Time    `json:"createdAt,omitempty"`
	EstablishedAt *time.Time    `json:"establishedAt,omitempty"`
	Headquarters  *Headquarters `json:"headquarters,omitempty"`
	ImprintPrefix *string       `json:"imprintPrefix,omitempty"`
	UpdatedAt     *time.Time    `json:"updatedAt,omitempty"`
}

// Update payload for PublishingHouse
type UpdatePublishingHouseInput struct {
	Name          *string       `json:"name,omitempty"`
	Authors       []*Author     `json:"authors,omitempty"`
	Books         []*Book       `json:"books,omitempty"`
	CreatedAt     *time.Time    `json:"createdAt,omitempty"`
	EstablishedAt *time.Time    `json:"establishedAt,omitempty"`
	Headquarters  *Headquarters `json:"headquarters,omitempty"`
	ImprintPrefix *string       `json:"imprintPrefix,omitempty"`
	UpdatedAt     *time.Time    `json:"updatedAt,omitempty"`
}

// Create payload for Tag
type CreateTagInput struct {
	Category    string     `json:"category,omitempty"`
	Name        string     `json:"name,omitempty"`
	Authors     []*Author  `json:"authors,omitempty"`
	Books       []*Book    `json:"books,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
}

// Update payload for Tag
type UpdateTagInput struct {
	Category    *string    `json:"category,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Authors     []*Author  `json:"authors,omitempty"`
	Books       []*Book    `json:"books,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
}
