package model

// Code generated by graphqlgen. DO NOT EDIT.

import (
	"github.com/99designs/gqlgen/graphql"
	"time"
)

// Custom scalar for UUID values
type UUID string

// Custom scalar for Time values
type Time time.Time

// Custom scalar for JSON objects
type JSON map[string]any

type OrderDirection string

const (
	OrderDirectionASC  OrderDirection = "ASC"
	OrderDirectionDESC OrderDirection = "DESC"
)

type FilterOperator string

const (
	FilterOperatorEQ     FilterOperator = "EQ"
	FilterOperatorNE     FilterOperator = "NE"
	FilterOperatorGT     FilterOperator = "GT"
	FilterOperatorLT     FilterOperator = "LT"
	FilterOperatorGTE    FilterOperator = "GTE"
	FilterOperatorLTE    FilterOperator = "LTE"
	FilterOperatorILIKE  FilterOperator = "ILIKE"
	FilterOperatorLIKE   FilterOperator = "LIKE"
	FilterOperatorIN     FilterOperator = "IN"
	FilterOperatorNOT_IN FilterOperator = "NOT_IN"
)

// CMS content entry (delivery API)
type Content struct {
	Id     string         `json:"id,omitempty"`
	Data   map[string]any `json:"data,omitempty"`
	Locale string         `json:"locale,omitempty"`
	Slug   string         `json:"slug,omitempty"`
	Status string         `json:"status,omitempty"`
	Type   string         `json:"type,omitempty"`
}

// Content connection
type ContentConnection struct {
	Edges    []*ContentEdge `json:"edges,omitempty"`
	PageInfo *PageInfo      `json:"pageInfo,omitempty"`
}

// Edge wrapper for Content
type ContentEdge struct {
	Cursor string   `json:"cursor,omitempty"`
	Node   *Content `json:"node,omitempty"`
}

// CMS menu entry (delivery API)
type Menu struct {
	Id       string         `json:"id,omitempty"`
	Code     string         `json:"code,omitempty"`
	Items    map[string]any `json:"items,omitempty"`
	Location string         `json:"location,omitempty"`
}

// Menu connection
type MenuConnection struct {
	Edges    []*MenuEdge `json:"edges,omitempty"`
	PageInfo *PageInfo   `json:"pageInfo,omitempty"`
}

// Edge wrapper for Menu
type MenuEdge struct {
	Cursor string `json:"cursor,omitempty"`
	Node   *Menu  `json:"node,omitempty"`
}

// CMS page entry (delivery API)
type Page struct {
	Id     string         `json:"id,omitempty"`
	Data   map[string]any `json:"data,omitempty"`
	Locale string         `json:"locale,omitempty"`
	Slug   string         `json:"slug,omitempty"`
	Status string         `json:"status,omitempty"`
	Title  string         `json:"title,omitempty"`
}

// Page connection
type PageConnection struct {
	Edges    []*PageEdge `json:"edges,omitempty"`
	PageInfo *PageInfo   `json:"pageInfo,omitempty"`
}

// Edge wrapper for Page
type PageEdge struct {
	Cursor string `json:"cursor,omitempty"`
	Node   *Page  `json:"node,omitempty"`
}

type PageInfo struct {
	Total           int    `json:"total,omitempty"`
	HasNextPage     bool   `json:"hasNextPage,omitempty"`
	HasPreviousPage bool   `json:"hasPreviousPage,omitempty"`
	StartCursor     string `json:"startCursor,omitempty"`
	EndCursor       string `json:"endCursor,omitempty"`
}

// Input type for pagination parameters
type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

// Input type for ordering parameters
type OrderByInput struct {
	Field     string          `json:"field,omitempty"`
	Direction *OrderDirection `json:"direction,omitempty"`
}

// Input type for filtering
type FilterInput struct {
	Field    string         `json:"field,omitempty"`
	Operator FilterOperator `json:"operator,omitempty"`
	Value    string         `json:"value,omitempty"`
}

// Create payload for Content
type CreateContentInput struct {
	Data   map[string]any `json:"data,omitempty"`
	Locale string         `json:"locale,omitempty"`
	Slug   string         `json:"slug,omitempty"`
	Status string         `json:"status,omitempty"`
	Type   string         `json:"type,omitempty"`
}

// Update payload for Content
type UpdateContentInput struct {
	Data   *map[string]any `json:"data,omitempty"`
	Locale *string         `json:"locale,omitempty"`
	Slug   *string         `json:"slug,omitempty"`
	Status *string         `json:"status,omitempty"`
	Type   *string         `json:"type,omitempty"`
}

// Create payload for Menu
type CreateMenuInput struct {
	Code     string         `json:"code,omitempty"`
	Items    map[string]any `json:"items,omitempty"`
	Location string         `json:"location,omitempty"`
}

// Update payload for Menu
type UpdateMenuInput struct {
	Code     *string         `json:"code,omitempty"`
	Items    *map[string]any `json:"items,omitempty"`
	Location *string         `json:"location,omitempty"`
}

// Create payload for Page
type CreatePageInput struct {
	Data   map[string]any `json:"data,omitempty"`
	Locale string         `json:"locale,omitempty"`
	Slug   string         `json:"slug,omitempty"`
	Status string         `json:"status,omitempty"`
	Title  *string        `json:"title,omitempty"`
}

// Update payload for Page
type UpdatePageInput struct {
	Data   *map[string]any `json:"data,omitempty"`
	Locale *string         `json:"locale,omitempty"`
	Slug   *string         `json:"slug,omitempty"`
	Status *string         `json:"status,omitempty"`
	Title  *string         `json:"title,omitempty"`
}

func MarshalUUID(v UUID) graphql.Marshaler {
	return graphql.MarshalString(string(v))
}

func UnmarshalUUID(v interface{}) (UUID, error) {
	s, err := graphql.UnmarshalString(v)
	if err != nil {
		return UUID(""), err
	}
	return UUID(s), nil
}

func MarshalTime(v Time) graphql.Marshaler {
	return graphql.MarshalTime(time.Time(v))
}

func UnmarshalTime(v interface{}) (Time, error) {
	t, err := graphql.UnmarshalTime(v)
	if err != nil {
		return Time{}, err
	}
	return Time(t), nil
}

func MarshalJSON(v JSON) graphql.Marshaler {
	return graphql.MarshalAny(map[string]any(v))
}

func UnmarshalJSON(v interface{}) (JSON, error) {
	out, err := graphql.UnmarshalMap(v)
	if err != nil {
		return nil, err
	}
	return JSON(out), nil
}
