package model

// Code generated by graphqlgen. DO NOT EDIT.

import (
	"github.com/99designs/gqlgen/graphql"
	"time"
)

// Custom scalar for UUID values
type UUID string

// Custom scalar for Time values
type Time time.Time

// Custom scalar for JSON objects
type JSON map[string]any

type OrderDirection string

const (
	OrderDirectionASC  OrderDirection = "ASC"
	OrderDirectionDESC OrderDirection = "DESC"
)

type FilterOperator string

const (
	FilterOperatorEQ     FilterOperator = "EQ"
	FilterOperatorNE     FilterOperator = "NE"
	FilterOperatorGT     FilterOperator = "GT"
	FilterOperatorLT     FilterOperator = "LT"
	FilterOperatorGTE    FilterOperator = "GTE"
	FilterOperatorLTE    FilterOperator = "LTE"
	FilterOperatorILIKE  FilterOperator = "ILIKE"
	FilterOperatorLIKE   FilterOperator = "LIKE"
	FilterOperatorIN     FilterOperator = "IN"
	FilterOperatorNOT_IN FilterOperator = "NOT_IN"
)

// Schema for Author
type Author struct {
	Id          []*Book          `json:"id,omitempty"`
	CreatedAt   *time.Time       `json:"created_at,omitempty"`
	UpdatedAt   *time.Time       `json:"updated_at,omitempty"`
	Active      bool             `json:"active,omitempty"`
	Books       []*Book          `json:"books,omitempty"`
	Email       string           `json:"email,omitempty"`
	FullName    string           `json:"full_name,omitempty"`
	HiredAt     *time.Time       `json:"hired_at,omitempty"`
	PenName     string           `json:"pen_name,omitempty"`
	Profile     *AuthorProfile   `json:"profile,omitempty"`
	Publisher   *PublishingHouse `json:"publisher,omitempty"`
	PublisherId *PublishingHouse `json:"publisher_id,omitempty"`
	Tags        []*Tag           `json:"tags,omitempty"`
}

// Author connection
type AuthorConnection struct {
	Edges    []*AuthorEdge `json:"edges,omitempty"`
	PageInfo *PageInfo     `json:"pageInfo,omitempty"`
}

// Edge wrapper for Author
type AuthorEdge struct {
	Cursor string  `json:"cursor,omitempty"`
	Node   *Author `json:"node,omitempty"`
}

// Schema for AuthorProfile
type AuthorProfile struct {
	Id            string  `json:"id,omitempty"`
	Author        *Author `json:"author,omitempty"`
	AuthorId      *Author `json:"author_id,omitempty"`
	Biography     string  `json:"biography,omitempty"`
	FavoriteGenre string  `json:"favorite_genre,omitempty"`
	WritingStyle  string  `json:"writing_style,omitempty"`
}

// AuthorProfile connection
type AuthorProfileConnection struct {
	Edges    []*AuthorProfileEdge `json:"edges,omitempty"`
	PageInfo *PageInfo            `json:"pageInfo,omitempty"`
}

// Edge wrapper for AuthorProfile
type AuthorProfileEdge struct {
	Cursor string         `json:"cursor,omitempty"`
	Node   *AuthorProfile `json:"node,omitempty"`
}

// Schema for Book
type Book struct {
	Id            []*Chapter       `json:"id,omitempty"`
	CreatedAt     *time.Time       `json:"created_at,omitempty"`
	UpdatedAt     *time.Time       `json:"updated_at,omitempty"`
	Author        *Author          `json:"author,omitempty"`
	AuthorId      *Author          `json:"author_id,omitempty"`
	Chapters      []*Chapter       `json:"chapters,omitempty"`
	Isbn          string           `json:"isbn,omitempty"`
	LastReprintAt *time.Time       `json:"last_reprint_at,omitempty"`
	Publisher     *PublishingHouse `json:"publisher,omitempty"`
	PublisherId   *PublishingHouse `json:"publisher_id,omitempty"`
	ReleaseDate   *time.Time       `json:"release_date,omitempty"`
	Status        string           `json:"status,omitempty"`
	Tags          []*Tag           `json:"tags,omitempty"`
	Title         string           `json:"title,omitempty"`
}

// Book connection
type BookConnection struct {
	Edges    []*BookEdge `json:"edges,omitempty"`
	PageInfo *PageInfo   `json:"pageInfo,omitempty"`
}

// Edge wrapper for Book
type BookEdge struct {
	Cursor string `json:"cursor,omitempty"`
	Node   *Book  `json:"node,omitempty"`
}

// Schema for Chapter
type Chapter struct {
	Id           string `json:"id,omitempty"`
	Book         *Book  `json:"book,omitempty"`
	BookId       *Book  `json:"book_id,omitempty"`
	ChapterIndex int    `json:"chapter_index,omitempty"`
	Title        string `json:"title,omitempty"`
	WordCount    int    `json:"word_count,omitempty"`
}

// Chapter connection
type ChapterConnection struct {
	Edges    []*ChapterEdge `json:"edges,omitempty"`
	PageInfo *PageInfo      `json:"pageInfo,omitempty"`
}

// Edge wrapper for Chapter
type ChapterEdge struct {
	Cursor string   `json:"cursor,omitempty"`
	Node   *Chapter `json:"node,omitempty"`
}

// Schema for Headquarters
type Headquarters struct {
	Id           string           `json:"id,omitempty"`
	AddressLine1 string           `json:"address_line1,omitempty"`
	AddressLine2 string           `json:"address_line2,omitempty"`
	City         string           `json:"city,omitempty"`
	Country      string           `json:"country,omitempty"`
	OpenedAt     *time.Time       `json:"opened_at,omitempty"`
	Publisher    *PublishingHouse `json:"publisher,omitempty"`
	PublisherId  *PublishingHouse `json:"publisher_id,omitempty"`
}

// Headquarters connection
type HeadquartersConnection struct {
	Edges    []*HeadquartersEdge `json:"edges,omitempty"`
	PageInfo *PageInfo           `json:"pageInfo,omitempty"`
}

// Edge wrapper for Headquarters
type HeadquartersEdge struct {
	Cursor string        `json:"cursor,omitempty"`
	Node   *Headquarters `json:"node,omitempty"`
}

type PageInfo struct {
	Total           int    `json:"total,omitempty"`
	HasNextPage     bool   `json:"hasNextPage,omitempty"`
	HasPreviousPage bool   `json:"hasPreviousPage,omitempty"`
	StartCursor     string `json:"startCursor,omitempty"`
	EndCursor       string `json:"endCursor,omitempty"`
}

// Schema for PublishingHouse
type PublishingHouse struct {
	Id            []*Book       `json:"id,omitempty"`
	CreatedAt     *time.Time    `json:"created_at,omitempty"`
	UpdatedAt     *time.Time    `json:"updated_at,omitempty"`
	Authors       []*Author     `json:"authors,omitempty"`
	Books         []*Book       `json:"books,omitempty"`
	EstablishedAt *time.Time    `json:"established_at,omitempty"`
	Headquarters  *Headquarters `json:"headquarters,omitempty"`
	ImprintPrefix string        `json:"imprint_prefix,omitempty"`
	Name          string        `json:"name,omitempty"`
}

// PublishingHouse connection
type PublishingHouseConnection struct {
	Edges    []*PublishingHouseEdge `json:"edges,omitempty"`
	PageInfo *PageInfo              `json:"pageInfo,omitempty"`
}

// Edge wrapper for PublishingHouse
type PublishingHouseEdge struct {
	Cursor string           `json:"cursor,omitempty"`
	Node   *PublishingHouse `json:"node,omitempty"`
}

// Schema for Tag
type Tag struct {
	Id          string     `json:"id,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Authors     []*Author  `json:"authors,omitempty"`
	Books       []*Book    `json:"books,omitempty"`
	Category    string     `json:"category,omitempty"`
	Description string     `json:"description,omitempty"`
	Name        string     `json:"name,omitempty"`
}

// Tag connection
type TagConnection struct {
	Edges    []*TagEdge `json:"edges,omitempty"`
	PageInfo *PageInfo  `json:"pageInfo,omitempty"`
}

// Edge wrapper for Tag
type TagEdge struct {
	Cursor string `json:"cursor,omitempty"`
	Node   *Tag   `json:"node,omitempty"`
}

// Input type for pagination parameters
type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

// Input type for ordering parameters
type OrderByInput struct {
	Field     string          `json:"field,omitempty"`
	Direction *OrderDirection `json:"direction,omitempty"`
}

// Input type for filtering
type FilterInput struct {
	Field    string         `json:"field,omitempty"`
	Operator FilterOperator `json:"operator,omitempty"`
	Value    string         `json:"value,omitempty"`
}

// Create payload for Author
type CreateAuthorInput struct {
	Active    bool       `json:"active,omitempty"`
	Email     string     `json:"email,omitempty"`
	FullName  string     `json:"fullName,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	HiredAt   *time.Time `json:"hiredAt,omitempty"`
	PenName   *string    `json:"penName,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Update payload for Author
type UpdateAuthorInput struct {
	Active    *bool      `json:"active,omitempty"`
	Email     *string    `json:"email,omitempty"`
	FullName  *string    `json:"fullName,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	HiredAt   *time.Time `json:"hiredAt,omitempty"`
	PenName   *string    `json:"penName,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Create payload for AuthorProfile
type CreateAuthorProfileInput struct {
	Biography     *string `json:"biography,omitempty"`
	FavoriteGenre *string `json:"favoriteGenre,omitempty"`
	WritingStyle  *string `json:"writingStyle,omitempty"`
}

// Update payload for AuthorProfile
type UpdateAuthorProfileInput struct {
	Biography     *string `json:"biography,omitempty"`
	FavoriteGenre *string `json:"favoriteGenre,omitempty"`
	WritingStyle  *string `json:"writingStyle,omitempty"`
}

// Create payload for Book
type CreateBookInput struct {
	Isbn          string     `json:"isbn,omitempty"`
	Status        string     `json:"status,omitempty"`
	Title         string     `json:"title,omitempty"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	LastReprintAt *time.Time `json:"lastReprintAt,omitempty"`
	ReleaseDate   *time.Time `json:"releaseDate,omitempty"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
}

// Update payload for Book
type UpdateBookInput struct {
	Isbn          *string    `json:"isbn,omitempty"`
	Status        *string    `json:"status,omitempty"`
	Title         *string    `json:"title,omitempty"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	LastReprintAt *time.Time `json:"lastReprintAt,omitempty"`
	ReleaseDate   *time.Time `json:"releaseDate,omitempty"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
}

// Create payload for Chapter
type CreateChapterInput struct {
	ChapterIndex int    `json:"chapterIndex,omitempty"`
	Title        string `json:"title,omitempty"`
	WordCount    int    `json:"wordCount,omitempty"`
}

// Update payload for Chapter
type UpdateChapterInput struct {
	ChapterIndex *int    `json:"chapterIndex,omitempty"`
	Title        *string `json:"title,omitempty"`
	WordCount    *int    `json:"wordCount,omitempty"`
}

// Create payload for Headquarters
type CreateHeadquartersInput struct {
	AddressLine1 string     `json:"addressLine1,omitempty"`
	City         string     `json:"city,omitempty"`
	Country      string     `json:"country,omitempty"`
	AddressLine2 *string    `json:"addressLine2,omitempty"`
	OpenedAt     *time.Time `json:"openedAt,omitempty"`
}

// Update payload for Headquarters
type UpdateHeadquartersInput struct {
	AddressLine1 *string    `json:"addressLine1,omitempty"`
	City         *string    `json:"city,omitempty"`
	Country      *string    `json:"country,omitempty"`
	AddressLine2 *string    `json:"addressLine2,omitempty"`
	OpenedAt     *time.Time `json:"openedAt,omitempty"`
}

// Create payload for PublishingHouse
type CreatePublishingHouseInput struct {
	Name          string     `json:"name,omitempty"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	EstablishedAt *time.Time `json:"establishedAt,omitempty"`
	ImprintPrefix *string    `json:"imprintPrefix,omitempty"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
}

// Update payload for PublishingHouse
type UpdatePublishingHouseInput struct {
	Name          *string    `json:"name,omitempty"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	EstablishedAt *time.Time `json:"establishedAt,omitempty"`
	ImprintPrefix *string    `json:"imprintPrefix,omitempty"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
}

// Create payload for Tag
type CreateTagInput struct {
	Category    string     `json:"category,omitempty"`
	Name        string     `json:"name,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
}

// Update payload for Tag
type UpdateTagInput struct {
	Category    *string    `json:"category,omitempty"`
	Name        *string    `json:"name,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
}

func MarshalUUID(v UUID) graphql.Marshaler {
	return graphql.MarshalString(string(v))
}

func UnmarshalUUID(v interface{}) (UUID, error) {
	s, err := graphql.UnmarshalString(v)
	if err != nil {
		return UUID(""), err
	}
	return UUID(s), nil
}

func MarshalTime(v Time) graphql.Marshaler {
	return graphql.MarshalTime(time.Time(v))
}

func UnmarshalTime(v interface{}) (Time, error) {
	t, err := graphql.UnmarshalTime(v)
	if err != nil {
		return Time{}, err
	}
	return Time(t), nil
}

func MarshalJSON(v JSON) graphql.Marshaler {
	return graphql.MarshalAny(map[string]any(v))
}

func UnmarshalJSON(v interface{}) (JSON, error) {
	out, err := graphql.UnmarshalMap(v)
	if err != nil {
		return nil, err
	}
	return JSON(out), nil
}
