package resolvers

// Code generated by graphqlgen. DO NOT EDIT.

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/goliatone/go-crud"
	repository "github.com/goliatone/go-repository-bun"
	"github.com/uptrace/bun"

	"github.com/goliatone/go-crud/examples/relationships-gql/graph/model"
)

type ScopeGuardFunc func(ctx context.Context, entity, action string) error
type ContextFactory func(ctx context.Context) crud.Context

type criteriaField struct {
	Column   string
	Relation string
}

var criteriaConfig = map[string]map[string]criteriaField{

	"Author": {

		"active":                  {Column: "active"},
		"books.authorid":          {Column: "books.author_id", Relation: "Books"},
		"books.createdat":         {Column: "books.created_at", Relation: "Books"},
		"books.id":                {Column: "books.id", Relation: "Books"},
		"books.isbn":              {Column: "books.isbn", Relation: "Books"},
		"books.lastreprintat":     {Column: "books.last_reprint_at", Relation: "Books"},
		"books.publisherid":       {Column: "books.publisher_id", Relation: "Books"},
		"books.releasedate":       {Column: "books.release_date", Relation: "Books"},
		"books.status":            {Column: "books.status", Relation: "Books"},
		"books.title":             {Column: "books.title", Relation: "Books"},
		"books.updatedat":         {Column: "books.updated_at", Relation: "Books"},
		"createdat":               {Column: "created_at"},
		"email":                   {Column: "email"},
		"fullname":                {Column: "full_name"},
		"hiredat":                 {Column: "hired_at"},
		"id":                      {Column: "id"},
		"penname":                 {Column: "pen_name"},
		"profile.authorid":        {Column: "profile.author_id", Relation: "Profile"},
		"profile.biography":       {Column: "profile.biography", Relation: "Profile"},
		"profile.favoritegenre":   {Column: "profile.favorite_genre", Relation: "Profile"},
		"profile.id":              {Column: "profile.id", Relation: "Profile"},
		"profile.writingstyle":    {Column: "profile.writing_style", Relation: "Profile"},
		"publisher.createdat":     {Column: "publisher.created_at", Relation: "Publisher"},
		"publisher.establishedat": {Column: "publisher.established_at", Relation: "Publisher"},
		"publisher.id":            {Column: "publisher.id", Relation: "Publisher"},
		"publisher.imprintprefix": {Column: "publisher.imprint_prefix", Relation: "Publisher"},
		"publisher.name":          {Column: "publisher.name", Relation: "Publisher"},
		"publisher.updatedat":     {Column: "publisher.updated_at", Relation: "Publisher"},
		"publisherid":             {Column: "publisher_id"},
		"tags.category":           {Column: "tags.category", Relation: "Tags"},
		"tags.createdat":          {Column: "tags.created_at", Relation: "Tags"},
		"tags.description":        {Column: "tags.description", Relation: "Tags"},
		"tags.id":                 {Column: "tags.id", Relation: "Tags"},
		"tags.name":               {Column: "tags.name", Relation: "Tags"},
		"updatedat":               {Column: "updated_at"},
	},

	"AuthorProfile": {

		"author.active":      {Column: "author.active", Relation: "Author"},
		"author.createdat":   {Column: "author.created_at", Relation: "Author"},
		"author.email":       {Column: "author.email", Relation: "Author"},
		"author.fullname":    {Column: "author.full_name", Relation: "Author"},
		"author.hiredat":     {Column: "author.hired_at", Relation: "Author"},
		"author.id":          {Column: "author.id", Relation: "Author"},
		"author.penname":     {Column: "author.pen_name", Relation: "Author"},
		"author.publisherid": {Column: "author.publisher_id", Relation: "Author"},
		"author.updatedat":   {Column: "author.updated_at", Relation: "Author"},
		"authorid":           {Column: "author_id"},
		"biography":          {Column: "biography"},
		"favoritegenre":      {Column: "favorite_genre"},
		"id":                 {Column: "id"},
		"writingstyle":       {Column: "writing_style"},
	},

	"Book": {

		"author.active":           {Column: "author.active", Relation: "Author"},
		"author.createdat":        {Column: "author.created_at", Relation: "Author"},
		"author.email":            {Column: "author.email", Relation: "Author"},
		"author.fullname":         {Column: "author.full_name", Relation: "Author"},
		"author.hiredat":          {Column: "author.hired_at", Relation: "Author"},
		"author.id":               {Column: "author.id", Relation: "Author"},
		"author.penname":          {Column: "author.pen_name", Relation: "Author"},
		"author.publisherid":      {Column: "author.publisher_id", Relation: "Author"},
		"author.updatedat":        {Column: "author.updated_at", Relation: "Author"},
		"authorid":                {Column: "author_id"},
		"chapters.bookid":         {Column: "chapters.book_id", Relation: "Chapters"},
		"chapters.chapterindex":   {Column: "chapters.chapter_index", Relation: "Chapters"},
		"chapters.id":             {Column: "chapters.id", Relation: "Chapters"},
		"chapters.title":          {Column: "chapters.title", Relation: "Chapters"},
		"chapters.wordcount":      {Column: "chapters.word_count", Relation: "Chapters"},
		"createdat":               {Column: "created_at"},
		"id":                      {Column: "id"},
		"isbn":                    {Column: "isbn"},
		"lastreprintat":           {Column: "last_reprint_at"},
		"publisher.createdat":     {Column: "publisher.created_at", Relation: "Publisher"},
		"publisher.establishedat": {Column: "publisher.established_at", Relation: "Publisher"},
		"publisher.id":            {Column: "publisher.id", Relation: "Publisher"},
		"publisher.imprintprefix": {Column: "publisher.imprint_prefix", Relation: "Publisher"},
		"publisher.name":          {Column: "publisher.name", Relation: "Publisher"},
		"publisher.updatedat":     {Column: "publisher.updated_at", Relation: "Publisher"},
		"publisherid":             {Column: "publisher_id"},
		"releasedate":             {Column: "release_date"},
		"status":                  {Column: "status"},
		"tags.category":           {Column: "tags.category", Relation: "Tags"},
		"tags.createdat":          {Column: "tags.created_at", Relation: "Tags"},
		"tags.description":        {Column: "tags.description", Relation: "Tags"},
		"tags.id":                 {Column: "tags.id", Relation: "Tags"},
		"tags.name":               {Column: "tags.name", Relation: "Tags"},
		"title":                   {Column: "title"},
		"updatedat":               {Column: "updated_at"},
	},

	"Chapter": {

		"book.authorid":      {Column: "book.author_id", Relation: "Book"},
		"book.createdat":     {Column: "book.created_at", Relation: "Book"},
		"book.id":            {Column: "book.id", Relation: "Book"},
		"book.isbn":          {Column: "book.isbn", Relation: "Book"},
		"book.lastreprintat": {Column: "book.last_reprint_at", Relation: "Book"},
		"book.publisherid":   {Column: "book.publisher_id", Relation: "Book"},
		"book.releasedate":   {Column: "book.release_date", Relation: "Book"},
		"book.status":        {Column: "book.status", Relation: "Book"},
		"book.title":         {Column: "book.title", Relation: "Book"},
		"book.updatedat":     {Column: "book.updated_at", Relation: "Book"},
		"bookid":             {Column: "book_id"},
		"chapterindex":       {Column: "chapter_index"},
		"id":                 {Column: "id"},
		"title":              {Column: "title"},
		"wordcount":          {Column: "word_count"},
	},

	"Headquarters": {

		"addressline1":            {Column: "address_line1"},
		"addressline2":            {Column: "address_line2"},
		"city":                    {Column: "city"},
		"country":                 {Column: "country"},
		"id":                      {Column: "id"},
		"openedat":                {Column: "opened_at"},
		"publisher.createdat":     {Column: "publisher.created_at", Relation: "Publisher"},
		"publisher.establishedat": {Column: "publisher.established_at", Relation: "Publisher"},
		"publisher.id":            {Column: "publisher.id", Relation: "Publisher"},
		"publisher.imprintprefix": {Column: "publisher.imprint_prefix", Relation: "Publisher"},
		"publisher.name":          {Column: "publisher.name", Relation: "Publisher"},
		"publisher.updatedat":     {Column: "publisher.updated_at", Relation: "Publisher"},
		"publisherid":             {Column: "publisher_id"},
	},

	"PublishingHouse": {

		"authors.active":            {Column: "authors.active", Relation: "Authors"},
		"authors.createdat":         {Column: "authors.created_at", Relation: "Authors"},
		"authors.email":             {Column: "authors.email", Relation: "Authors"},
		"authors.fullname":          {Column: "authors.full_name", Relation: "Authors"},
		"authors.hiredat":           {Column: "authors.hired_at", Relation: "Authors"},
		"authors.id":                {Column: "authors.id", Relation: "Authors"},
		"authors.penname":           {Column: "authors.pen_name", Relation: "Authors"},
		"authors.publisherid":       {Column: "authors.publisher_id", Relation: "Authors"},
		"authors.updatedat":         {Column: "authors.updated_at", Relation: "Authors"},
		"books.authorid":            {Column: "books.author_id", Relation: "Books"},
		"books.createdat":           {Column: "books.created_at", Relation: "Books"},
		"books.id":                  {Column: "books.id", Relation: "Books"},
		"books.isbn":                {Column: "books.isbn", Relation: "Books"},
		"books.lastreprintat":       {Column: "books.last_reprint_at", Relation: "Books"},
		"books.publisherid":         {Column: "books.publisher_id", Relation: "Books"},
		"books.releasedate":         {Column: "books.release_date", Relation: "Books"},
		"books.status":              {Column: "books.status", Relation: "Books"},
		"books.title":               {Column: "books.title", Relation: "Books"},
		"books.updatedat":           {Column: "books.updated_at", Relation: "Books"},
		"createdat":                 {Column: "created_at"},
		"establishedat":             {Column: "established_at"},
		"headquarters.addressline1": {Column: "headquarters.address_line1", Relation: "Headquarters"},
		"headquarters.addressline2": {Column: "headquarters.address_line2", Relation: "Headquarters"},
		"headquarters.city":         {Column: "headquarters.city", Relation: "Headquarters"},
		"headquarters.country":      {Column: "headquarters.country", Relation: "Headquarters"},
		"headquarters.id":           {Column: "headquarters.id", Relation: "Headquarters"},
		"headquarters.openedat":     {Column: "headquarters.opened_at", Relation: "Headquarters"},
		"headquarters.publisherid":  {Column: "headquarters.publisher_id", Relation: "Headquarters"},
		"id":                        {Column: "id"},
		"imprintprefix":             {Column: "imprint_prefix"},
		"name":                      {Column: "name"},
		"updatedat":                 {Column: "updated_at"},
	},

	"Tag": {

		"authors.active":      {Column: "authors.active", Relation: "Authors"},
		"authors.createdat":   {Column: "authors.created_at", Relation: "Authors"},
		"authors.email":       {Column: "authors.email", Relation: "Authors"},
		"authors.fullname":    {Column: "authors.full_name", Relation: "Authors"},
		"authors.hiredat":     {Column: "authors.hired_at", Relation: "Authors"},
		"authors.id":          {Column: "authors.id", Relation: "Authors"},
		"authors.penname":     {Column: "authors.pen_name", Relation: "Authors"},
		"authors.publisherid": {Column: "authors.publisher_id", Relation: "Authors"},
		"authors.updatedat":   {Column: "authors.updated_at", Relation: "Authors"},
		"books.authorid":      {Column: "books.author_id", Relation: "Books"},
		"books.createdat":     {Column: "books.created_at", Relation: "Books"},
		"books.id":            {Column: "books.id", Relation: "Books"},
		"books.isbn":          {Column: "books.isbn", Relation: "Books"},
		"books.lastreprintat": {Column: "books.last_reprint_at", Relation: "Books"},
		"books.publisherid":   {Column: "books.publisher_id", Relation: "Books"},
		"books.releasedate":   {Column: "books.release_date", Relation: "Books"},
		"books.status":        {Column: "books.status", Relation: "Books"},
		"books.title":         {Column: "books.title", Relation: "Books"},
		"books.updatedat":     {Column: "books.updated_at", Relation: "Books"},
		"category":            {Column: "category"},
		"createdat":           {Column: "created_at"},
		"description":         {Column: "description"},
		"id":                  {Column: "id"},
		"name":                {Column: "name"},
	},
}

func (r *Resolver) crudContext(ctx context.Context) crud.Context {
	if r.ContextFactory != nil {
		return r.ContextFactory(ctx)
	}
	return nil
}

func (r *Resolver) guard(ctx context.Context, entity, action string) error {
	if r.ScopeGuard != nil {
		if err := r.ScopeGuard(ctx, entity, action); err != nil {
			return err
		}
	}
	return nil
}

func buildCriteria(entity string, p *model.PaginationInput, order []*model.OrderByInput, filters []*model.FilterInput) []repository.SelectCriteria {
	fields := criteriaConfig[entity]
	criteria := make([]repository.SelectCriteria, 0, 1+len(order)+len(filters))

	if p != nil {
		if p.Limit != nil && *p.Limit > 0 {
			limit := *p.Limit
			criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
				return q.Limit(limit)
			})
		}
		if p.Offset != nil && *p.Offset >= 0 {
			offset := *p.Offset
			criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
				return q.Offset(offset)
			})
		}
	}

	for _, ob := range order {
		if ob == nil || ob.Field == "" {
			continue
		}
		field, ok := lookupField(fields, ob.Field)
		if !ok {
			continue
		}

		dir := normalizeDirection(ob.Direction)
		column := field.Column
		relation := field.Relation

		criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
			if relation != "" {
				q = q.Relation(relation)
			}
			return q.OrderExpr("? ?", bun.Safe(column), bun.Safe(dir))
		})
	}

	for _, filter := range filters {
		if filter == nil || filter.Field == "" {
			continue
		}
		field, ok := lookupField(fields, filter.Field)
		if !ok {
			continue
		}

		op := normalizeOperator(filter.Operator)
		if op == "" {
			continue
		}

		value := strings.TrimSpace(filter.Value)
		if value == "" {
			continue
		}

		column := field.Column
		relation := field.Relation

		switch op {
		case "IN", "NOT IN":
			values := splitList(value)
			if len(values) == 0 {
				continue
			}
			criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
				if relation != "" {
					q = q.Relation(relation)
				}
				expr := fmt.Sprintf("%s IN (?)", column)
				if op == "NOT IN" {
					expr = fmt.Sprintf("%s NOT IN (?)", column)
				}
				return q.Where(expr, bun.In(values))
			})
		default:
			criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
				if relation != "" {
					q = q.Relation(relation)
				}
				return q.Where(fmt.Sprintf("%s %s ?", column, op), value)
			})
		}
	}

	return criteria
}

func normalizeDirection(dir *model.OrderDirection) string {
	if dir == nil {
		return "ASC"
	}
	value := strings.ToUpper(string(*dir))
	if value != "DESC" {
		return "ASC"
	}
	return value
}

func normalizeOperator(op model.FilterOperator) string {
	switch strings.ToUpper(string(op)) {
	case "EQ":
		return "="
	case "NE":
		return "<>"
	case "GT":
		return ">"
	case "LT":
		return "<"
	case "GTE":
		return ">="
	case "LTE":
		return "<="
	case "ILIKE":
		return "ILIKE"
	case "LIKE":
		return "LIKE"
	case "IN":
		return "IN"
	case "NOT_IN":
		return "NOT IN"
	default:
		return ""
	}
}

func lookupField(fields map[string]criteriaField, raw string) (criteriaField, bool) {
	if len(fields) == 0 {
		return criteriaField{}, false
	}
	key := strings.ToLower(strings.TrimSpace(raw))
	value, ok := fields[key]
	return value, ok
}

func splitList(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		val := strings.TrimSpace(part)
		if val == "" {
			continue
		}
		out = append(out, val)
	}
	return out
}

func applyInput[T any, I any](dst *T, src I) {
	if dst == nil {
		return
	}

	dv := reflect.ValueOf(dst)
	if dv.Kind() != reflect.Pointer || dv.IsNil() {
		return
	}

	sv := reflect.ValueOf(src)
	if sv.Kind() == reflect.Pointer {
		if sv.IsNil() {
			return
		}
		sv = sv.Elem()
	}

	dv = dv.Elem()

	for i := 0; i < sv.NumField(); i++ {
		sf := sv.Field(i)
		df := dv.FieldByName(sv.Type().Field(i).Name)
		if !df.IsValid() || !df.CanSet() {
			continue
		}
		if sf.Kind() == reflect.Pointer {
			if sf.IsNil() {
				continue
			}
			sf = sf.Elem()
		}
		assignField(df, sf)
	}
}

func assignField(dst, src reflect.Value) {
	switch {
	case !dst.IsValid() || !dst.CanSet():
		return
	case src.Type().AssignableTo(dst.Type()):
		dst.Set(src)
	case dst.Kind() == reflect.Pointer && src.Type().AssignableTo(dst.Type().Elem()):
		if dst.IsNil() {
			dst.Set(reflect.New(dst.Type().Elem()))
		}
		dst.Elem().Set(src)
	case src.Type().ConvertibleTo(dst.Type()):
		dst.Set(src.Convert(dst.Type()))
	case dst.Kind() == reflect.Pointer && src.Type().ConvertibleTo(dst.Type().Elem()):
		if dst.IsNil() {
			dst.Set(reflect.New(dst.Type().Elem()))
		}
		dst.Elem().Set(src.Convert(dst.Type().Elem()))
	}
}

func setID[T any](dst *T, id string) {
	dv := reflect.ValueOf(dst).Elem()
	for _, name := range []string{"ID", "Id"} {
		f := dv.FieldByName(name)
		if f.IsValid() && f.CanSet() && f.Kind() == reflect.String {
			f.SetString(id)
			return
		}
	}
}

func asUUID(id string) model.UUID { return model.UUID(id) }

func asTime(t *time.Time) *model.Time {
	if t == nil {
		return nil
	}
	val := model.Time(*t)
	return &val
}

func setUUID(dst *string, data model.UUID) {
	*dst = string(data)
}

func setUUIDPtr(dst **string, data *model.UUID) {
	if data == nil {
		*dst = nil
		return
	}
	val := string(*data)
	*dst = &val
}

func setTimePtr(dst **time.Time, data *model.Time) {
	if data == nil {
		*dst = nil
		return
	}
	val := time.Time(*data)
	*dst = &val
}

func (r *Resolver) AuthorService() crud.Service[model.Author] {
	if r.AuthorSvc == nil {
		panic("AuthorService is not configured on Resolver")
	}
	return r.AuthorSvc
}

func (r *Resolver) GetAuthor(ctx context.Context, id string) (*model.Author, error) {
	if err := r.guard(ctx, "Author", "show"); err != nil {
		return nil, err
	}
	record, err := r.AuthorService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListAuthor(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) ([]*model.Author, error) {
	if err := r.guard(ctx, "Author", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("Author", pagination, orderBy, filter)
	records, _, err := r.AuthorService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Author, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreateAuthor(ctx context.Context, input model.CreateAuthorInput) (*model.Author, error) {
	if err := r.guard(ctx, "Author", "create"); err != nil {
		return nil, err
	}
	var record model.Author
	applyInput(&record, input)
	record, err := r.AuthorService().Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateAuthor(ctx context.Context, id string, input model.UpdateAuthorInput) (*model.Author, error) {
	if err := r.guard(ctx, "Author", "update"); err != nil {
		return nil, err
	}
	record, err := r.AuthorService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = r.AuthorService().Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteAuthor(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "Author", "delete"); err != nil {
		return false, err
	}
	var record model.Author
	setID(&record, id)
	if err := r.AuthorService().Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}

func (r *Resolver) AuthorProfileService() crud.Service[model.AuthorProfile] {
	if r.AuthorProfileSvc == nil {
		panic("AuthorProfileService is not configured on Resolver")
	}
	return r.AuthorProfileSvc
}

func (r *Resolver) GetAuthorProfile(ctx context.Context, id string) (*model.AuthorProfile, error) {
	if err := r.guard(ctx, "AuthorProfile", "show"); err != nil {
		return nil, err
	}
	record, err := r.AuthorProfileService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListAuthorProfile(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) ([]*model.AuthorProfile, error) {
	if err := r.guard(ctx, "AuthorProfile", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("AuthorProfile", pagination, orderBy, filter)
	records, _, err := r.AuthorProfileService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.AuthorProfile, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreateAuthorProfile(ctx context.Context, input model.CreateAuthorProfileInput) (*model.AuthorProfile, error) {
	if err := r.guard(ctx, "AuthorProfile", "create"); err != nil {
		return nil, err
	}
	var record model.AuthorProfile
	applyInput(&record, input)
	record, err := r.AuthorProfileService().Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateAuthorProfile(ctx context.Context, id string, input model.UpdateAuthorProfileInput) (*model.AuthorProfile, error) {
	if err := r.guard(ctx, "AuthorProfile", "update"); err != nil {
		return nil, err
	}
	record, err := r.AuthorProfileService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = r.AuthorProfileService().Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteAuthorProfile(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "AuthorProfile", "delete"); err != nil {
		return false, err
	}
	var record model.AuthorProfile
	setID(&record, id)
	if err := r.AuthorProfileService().Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}

func (r *Resolver) BookService() crud.Service[model.Book] {
	if r.BookSvc == nil {
		panic("BookService is not configured on Resolver")
	}
	return r.BookSvc
}

func (r *Resolver) GetBook(ctx context.Context, id string) (*model.Book, error) {
	if err := r.guard(ctx, "Book", "show"); err != nil {
		return nil, err
	}
	record, err := r.BookService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListBook(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) ([]*model.Book, error) {
	if err := r.guard(ctx, "Book", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("Book", pagination, orderBy, filter)
	records, _, err := r.BookService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Book, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreateBook(ctx context.Context, input model.CreateBookInput) (*model.Book, error) {
	if err := r.guard(ctx, "Book", "create"); err != nil {
		return nil, err
	}
	var record model.Book
	applyInput(&record, input)
	record, err := r.BookService().Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateBook(ctx context.Context, id string, input model.UpdateBookInput) (*model.Book, error) {
	if err := r.guard(ctx, "Book", "update"); err != nil {
		return nil, err
	}
	record, err := r.BookService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = r.BookService().Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteBook(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "Book", "delete"); err != nil {
		return false, err
	}
	var record model.Book
	setID(&record, id)
	if err := r.BookService().Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}

func (r *Resolver) ChapterService() crud.Service[model.Chapter] {
	if r.ChapterSvc == nil {
		panic("ChapterService is not configured on Resolver")
	}
	return r.ChapterSvc
}

func (r *Resolver) GetChapter(ctx context.Context, id string) (*model.Chapter, error) {
	if err := r.guard(ctx, "Chapter", "show"); err != nil {
		return nil, err
	}
	record, err := r.ChapterService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListChapter(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) ([]*model.Chapter, error) {
	if err := r.guard(ctx, "Chapter", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("Chapter", pagination, orderBy, filter)
	records, _, err := r.ChapterService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Chapter, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreateChapter(ctx context.Context, input model.CreateChapterInput) (*model.Chapter, error) {
	if err := r.guard(ctx, "Chapter", "create"); err != nil {
		return nil, err
	}
	var record model.Chapter
	applyInput(&record, input)
	record, err := r.ChapterService().Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateChapter(ctx context.Context, id string, input model.UpdateChapterInput) (*model.Chapter, error) {
	if err := r.guard(ctx, "Chapter", "update"); err != nil {
		return nil, err
	}
	record, err := r.ChapterService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = r.ChapterService().Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteChapter(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "Chapter", "delete"); err != nil {
		return false, err
	}
	var record model.Chapter
	setID(&record, id)
	if err := r.ChapterService().Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}

func (r *Resolver) HeadquartersService() crud.Service[model.Headquarters] {
	if r.HeadquartersSvc == nil {
		panic("HeadquartersService is not configured on Resolver")
	}
	return r.HeadquartersSvc
}

func (r *Resolver) GetHeadquarters(ctx context.Context, id string) (*model.Headquarters, error) {
	if err := r.guard(ctx, "Headquarters", "show"); err != nil {
		return nil, err
	}
	record, err := r.HeadquartersService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListHeadquarters(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) ([]*model.Headquarters, error) {
	if err := r.guard(ctx, "Headquarters", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("Headquarters", pagination, orderBy, filter)
	records, _, err := r.HeadquartersService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Headquarters, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreateHeadquarters(ctx context.Context, input model.CreateHeadquartersInput) (*model.Headquarters, error) {
	if err := r.guard(ctx, "Headquarters", "create"); err != nil {
		return nil, err
	}
	var record model.Headquarters
	applyInput(&record, input)
	record, err := r.HeadquartersService().Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateHeadquarters(ctx context.Context, id string, input model.UpdateHeadquartersInput) (*model.Headquarters, error) {
	if err := r.guard(ctx, "Headquarters", "update"); err != nil {
		return nil, err
	}
	record, err := r.HeadquartersService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = r.HeadquartersService().Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteHeadquarters(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "Headquarters", "delete"); err != nil {
		return false, err
	}
	var record model.Headquarters
	setID(&record, id)
	if err := r.HeadquartersService().Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}

func (r *Resolver) PublishingHouseService() crud.Service[model.PublishingHouse] {
	if r.PublishingHouseSvc == nil {
		panic("PublishingHouseService is not configured on Resolver")
	}
	return r.PublishingHouseSvc
}

func (r *Resolver) GetPublishingHouse(ctx context.Context, id string) (*model.PublishingHouse, error) {
	if err := r.guard(ctx, "PublishingHouse", "show"); err != nil {
		return nil, err
	}
	record, err := r.PublishingHouseService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListPublishingHouse(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) ([]*model.PublishingHouse, error) {
	if err := r.guard(ctx, "PublishingHouse", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("PublishingHouse", pagination, orderBy, filter)
	records, _, err := r.PublishingHouseService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.PublishingHouse, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreatePublishingHouse(ctx context.Context, input model.CreatePublishingHouseInput) (*model.PublishingHouse, error) {
	if err := r.guard(ctx, "PublishingHouse", "create"); err != nil {
		return nil, err
	}
	var record model.PublishingHouse
	applyInput(&record, input)
	record, err := r.PublishingHouseService().Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdatePublishingHouse(ctx context.Context, id string, input model.UpdatePublishingHouseInput) (*model.PublishingHouse, error) {
	if err := r.guard(ctx, "PublishingHouse", "update"); err != nil {
		return nil, err
	}
	record, err := r.PublishingHouseService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = r.PublishingHouseService().Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeletePublishingHouse(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "PublishingHouse", "delete"); err != nil {
		return false, err
	}
	var record model.PublishingHouse
	setID(&record, id)
	if err := r.PublishingHouseService().Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}

func (r *Resolver) TagService() crud.Service[model.Tag] {
	if r.TagSvc == nil {
		panic("TagService is not configured on Resolver")
	}
	return r.TagSvc
}

func (r *Resolver) GetTag(ctx context.Context, id string) (*model.Tag, error) {
	if err := r.guard(ctx, "Tag", "show"); err != nil {
		return nil, err
	}
	record, err := r.TagService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListTag(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) ([]*model.Tag, error) {
	if err := r.guard(ctx, "Tag", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("Tag", pagination, orderBy, filter)
	records, _, err := r.TagService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Tag, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.Tag, error) {
	if err := r.guard(ctx, "Tag", "create"); err != nil {
		return nil, err
	}
	var record model.Tag
	applyInput(&record, input)
	record, err := r.TagService().Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateTag(ctx context.Context, id string, input model.UpdateTagInput) (*model.Tag, error) {
	if err := r.guard(ctx, "Tag", "update"); err != nil {
		return nil, err
	}
	record, err := r.TagService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = r.TagService().Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteTag(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "Tag", "delete"); err != nil {
		return false, err
	}
	var record model.Tag
	setID(&record, id)
	if err := r.TagService().Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}
