package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"errors"
	"fmt"

	"github.com/goliatone/go-crud/examples/relationships-gql/graph/generated"
	"github.com/goliatone/go-crud/examples/relationships-gql/graph/model"
)

// ID is the resolver for the id field.
func (r *authorResolver) ID(ctx context.Context, obj *model.Author) (model.UUID, error) {
	return asUUID(obj.Id), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *authorResolver) CreatedAt(ctx context.Context, obj *model.Author) (*model.Time, error) {
	return asTime(obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *authorResolver) UpdatedAt(ctx context.Context, obj *model.Author) (*model.Time, error) {
	return asTime(obj.UpdatedAt), nil
}

// HiredAt is the resolver for the hiredAt field.
func (r *authorResolver) HiredAt(ctx context.Context, obj *model.Author) (*model.Time, error) {
	return asTime(obj.HiredAt), nil
}

// PublisherID is the resolver for the publisherId field.
func (r *authorResolver) PublisherID(ctx context.Context, obj *model.Author) (model.UUID, error) {
	return asUUID(obj.PublisherId), nil
}

// ID is the resolver for the id field.
func (r *authorProfileResolver) ID(ctx context.Context, obj *model.AuthorProfile) (model.UUID, error) {
	return asUUID(obj.Id), nil
}

// AuthorID is the resolver for the authorId field.
func (r *authorProfileResolver) AuthorID(ctx context.Context, obj *model.AuthorProfile) (model.UUID, error) {
	return asUUID(obj.AuthorId), nil
}

// ID is the resolver for the id field.
func (r *bookResolver) ID(ctx context.Context, obj *model.Book) (model.UUID, error) {
	return asUUID(obj.Id), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *bookResolver) CreatedAt(ctx context.Context, obj *model.Book) (*model.Time, error) {
	return asTime(obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *bookResolver) UpdatedAt(ctx context.Context, obj *model.Book) (*model.Time, error) {
	return asTime(obj.UpdatedAt), nil
}

// AuthorID is the resolver for the authorId field.
func (r *bookResolver) AuthorID(ctx context.Context, obj *model.Book) (model.UUID, error) {
	return asUUID(obj.AuthorId), nil
}

// LastReprintAt is the resolver for the lastReprintAt field.
func (r *bookResolver) LastReprintAt(ctx context.Context, obj *model.Book) (*model.Time, error) {
	return asTime(obj.LastReprintAt), nil
}

// PublisherID is the resolver for the publisherId field.
func (r *bookResolver) PublisherID(ctx context.Context, obj *model.Book) (model.UUID, error) {
	return asUUID(obj.PublisherId), nil
}

// ReleaseDate is the resolver for the releaseDate field.
func (r *bookResolver) ReleaseDate(ctx context.Context, obj *model.Book) (*model.Time, error) {
	return asTime(obj.ReleaseDate), nil
}

// ID is the resolver for the id field.
func (r *chapterResolver) ID(ctx context.Context, obj *model.Chapter) (model.UUID, error) {
	return asUUID(obj.Id), nil
}

// BookID is the resolver for the bookId field.
func (r *chapterResolver) BookID(ctx context.Context, obj *model.Chapter) (model.UUID, error) {
	return asUUID(obj.BookId), nil
}

// ID is the resolver for the id field.
func (r *headquartersResolver) ID(ctx context.Context, obj *model.Headquarters) (model.UUID, error) {
	return asUUID(obj.Id), nil
}

// OpenedAt is the resolver for the openedAt field.
func (r *headquartersResolver) OpenedAt(ctx context.Context, obj *model.Headquarters) (*model.Time, error) {
	return asTime(obj.OpenedAt), nil
}

// PublisherID is the resolver for the publisherId field.
func (r *headquartersResolver) PublisherID(ctx context.Context, obj *model.Headquarters) (model.UUID, error) {
	return asUUID(obj.PublisherId), nil
}

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input model.CreateAuthorInput) (*model.Author, error) {
	return r.Resolver.CreateAuthor(ctx, input)
}

// UpdateAuthor is the resolver for the updateAuthor field.
func (r *mutationResolver) UpdateAuthor(ctx context.Context, id model.UUID, input model.UpdateAuthorInput) (*model.Author, error) {
	return r.Resolver.UpdateAuthor(ctx, string(id), input)
}

// DeleteAuthor is the resolver for the deleteAuthor field.
func (r *mutationResolver) DeleteAuthor(ctx context.Context, id model.UUID) (bool, error) {
	return r.Resolver.DeleteAuthor(ctx, string(id))
}

// CreateAuthorProfile is the resolver for the createAuthorProfile field.
func (r *mutationResolver) CreateAuthorProfile(ctx context.Context, input model.CreateAuthorProfileInput) (*model.AuthorProfile, error) {
	return r.Resolver.CreateAuthorProfile(ctx, input)
}

// UpdateAuthorProfile is the resolver for the updateAuthorProfile field.
func (r *mutationResolver) UpdateAuthorProfile(ctx context.Context, id model.UUID, input model.UpdateAuthorProfileInput) (*model.AuthorProfile, error) {
	return r.Resolver.UpdateAuthorProfile(ctx, string(id), input)
}

// DeleteAuthorProfile is the resolver for the deleteAuthorProfile field.
func (r *mutationResolver) DeleteAuthorProfile(ctx context.Context, id model.UUID) (bool, error) {
	return r.Resolver.DeleteAuthorProfile(ctx, string(id))
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.CreateBookInput) (*model.Book, error) {
	return r.Resolver.CreateBook(ctx, input)
}

// UpdateBook is the resolver for the updateBook field.
func (r *mutationResolver) UpdateBook(ctx context.Context, id model.UUID, input model.UpdateBookInput) (*model.Book, error) {
	return r.Resolver.UpdateBook(ctx, string(id), input)
}

// DeleteBook is the resolver for the deleteBook field.
func (r *mutationResolver) DeleteBook(ctx context.Context, id model.UUID) (bool, error) {
	return r.Resolver.DeleteBook(ctx, string(id))
}

// CreateChapter is the resolver for the createChapter field.
func (r *mutationResolver) CreateChapter(ctx context.Context, input model.CreateChapterInput) (*model.Chapter, error) {
	return r.Resolver.CreateChapter(ctx, input)
}

// UpdateChapter is the resolver for the updateChapter field.
func (r *mutationResolver) UpdateChapter(ctx context.Context, id model.UUID, input model.UpdateChapterInput) (*model.Chapter, error) {
	return r.Resolver.UpdateChapter(ctx, string(id), input)
}

// DeleteChapter is the resolver for the deleteChapter field.
func (r *mutationResolver) DeleteChapter(ctx context.Context, id model.UUID) (bool, error) {
	return r.Resolver.DeleteChapter(ctx, string(id))
}

// CreateHeadquarters is the resolver for the createHeadquarters field.
func (r *mutationResolver) CreateHeadquarters(ctx context.Context, input model.CreateHeadquartersInput) (*model.Headquarters, error) {
	return r.Resolver.CreateHeadquarters(ctx, input)
}

// UpdateHeadquarters is the resolver for the updateHeadquarters field.
func (r *mutationResolver) UpdateHeadquarters(ctx context.Context, id model.UUID, input model.UpdateHeadquartersInput) (*model.Headquarters, error) {
	return r.Resolver.UpdateHeadquarters(ctx, string(id), input)
}

// DeleteHeadquarters is the resolver for the deleteHeadquarters field.
func (r *mutationResolver) DeleteHeadquarters(ctx context.Context, id model.UUID) (bool, error) {
	return r.Resolver.DeleteHeadquarters(ctx, string(id))
}

// CreatePublishingHouse is the resolver for the createPublishingHouse field.
func (r *mutationResolver) CreatePublishingHouse(ctx context.Context, input model.CreatePublishingHouseInput) (*model.PublishingHouse, error) {
	return r.Resolver.CreatePublishingHouse(ctx, input)
}

// UpdatePublishingHouse is the resolver for the updatePublishingHouse field.
func (r *mutationResolver) UpdatePublishingHouse(ctx context.Context, id model.UUID, input model.UpdatePublishingHouseInput) (*model.PublishingHouse, error) {
	return r.Resolver.UpdatePublishingHouse(ctx, string(id), input)
}

// DeletePublishingHouse is the resolver for the deletePublishingHouse field.
func (r *mutationResolver) DeletePublishingHouse(ctx context.Context, id model.UUID) (bool, error) {
	return r.Resolver.DeletePublishingHouse(ctx, string(id))
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.Tag, error) {
	tag, err := r.Resolver.CreateTag(ctx, input)
	if err == nil && tag != nil {
		_ = r.Events.Publish(ctx, tagCreatedTopic, *tag)
	}
	return tag, err
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, id model.UUID, input model.UpdateTagInput) (*model.Tag, error) {
	tag, err := r.Resolver.UpdateTag(ctx, string(id), input)
	if err == nil && tag != nil {
		_ = r.Events.Publish(ctx, tagUpdatedTopic, *tag)
	}
	return tag, err
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id model.UUID) (bool, error) {
	if err := r.guard(ctx, "Tag", "delete"); err != nil {
		return false, err
	}
	if tag, err := r.TagService().Show(r.crudContext(ctx), string(id), nil); err == nil {
		_ = r.Events.Publish(ctx, tagDeletedTopic, tag)
	}
	return r.Resolver.DeleteTag(ctx, string(id))
}

// ID is the resolver for the id field.
func (r *publishingHouseResolver) ID(ctx context.Context, obj *model.PublishingHouse) (model.UUID, error) {
	return asUUID(obj.Id), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *publishingHouseResolver) CreatedAt(ctx context.Context, obj *model.PublishingHouse) (*model.Time, error) {
	return asTime(obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *publishingHouseResolver) UpdatedAt(ctx context.Context, obj *model.PublishingHouse) (*model.Time, error) {
	return asTime(obj.UpdatedAt), nil
}

// EstablishedAt is the resolver for the establishedAt field.
func (r *publishingHouseResolver) EstablishedAt(ctx context.Context, obj *model.PublishingHouse) (*model.Time, error) {
	return asTime(obj.EstablishedAt), nil
}

// GetAuthor is the resolver for the getAuthor field.
func (r *queryResolver) GetAuthor(ctx context.Context, id model.UUID) (*model.Author, error) {
	return r.Resolver.GetAuthor(ctx, string(id))
}

// ListAuthor is the resolver for the listAuthor field.
func (r *queryResolver) ListAuthor(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.AuthorConnection, error) {
	return r.Resolver.ListAuthor(ctx, pagination, orderBy, filter)
}

// GetAuthorProfile is the resolver for the getAuthorProfile field.
func (r *queryResolver) GetAuthorProfile(ctx context.Context, id model.UUID) (*model.AuthorProfile, error) {
	return r.Resolver.GetAuthorProfile(ctx, string(id))
}

// ListAuthorProfile is the resolver for the listAuthorProfile field.
func (r *queryResolver) ListAuthorProfile(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.AuthorProfileConnection, error) {
	return r.Resolver.ListAuthorProfile(ctx, pagination, orderBy, filter)
}

// GetBook is the resolver for the getBook field.
func (r *queryResolver) GetBook(ctx context.Context, id model.UUID) (*model.Book, error) {
	return r.Resolver.GetBook(ctx, string(id))
}

// ListBook is the resolver for the listBook field.
func (r *queryResolver) ListBook(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.BookConnection, error) {
	return r.Resolver.ListBook(ctx, pagination, orderBy, filter)
}

// GetChapter is the resolver for the getChapter field.
func (r *queryResolver) GetChapter(ctx context.Context, id model.UUID) (*model.Chapter, error) {
	return r.Resolver.GetChapter(ctx, string(id))
}

// ListChapter is the resolver for the listChapter field.
func (r *queryResolver) ListChapter(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.ChapterConnection, error) {
	return r.Resolver.ListChapter(ctx, pagination, orderBy, filter)
}

// GetHeadquarters is the resolver for the getHeadquarters field.
func (r *queryResolver) GetHeadquarters(ctx context.Context, id model.UUID) (*model.Headquarters, error) {
	return r.Resolver.GetHeadquarters(ctx, string(id))
}

// ListHeadquarters is the resolver for the listHeadquarters field.
func (r *queryResolver) ListHeadquarters(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.HeadquartersConnection, error) {
	return r.Resolver.ListHeadquarters(ctx, pagination, orderBy, filter)
}

// GetPublishingHouse is the resolver for the getPublishingHouse field.
func (r *queryResolver) GetPublishingHouse(ctx context.Context, id model.UUID) (*model.PublishingHouse, error) {
	return r.Resolver.GetPublishingHouse(ctx, string(id))
}

// ListPublishingHouse is the resolver for the listPublishingHouse field.
func (r *queryResolver) ListPublishingHouse(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.PublishingHouseConnection, error) {
	return r.Resolver.ListPublishingHouse(ctx, pagination, orderBy, filter)
}

// GetTag is the resolver for the getTag field.
func (r *queryResolver) GetTag(ctx context.Context, id model.UUID) (*model.Tag, error) {
	return r.Resolver.GetTag(ctx, string(id))
}

// ListTag is the resolver for the listTag field.
func (r *queryResolver) ListTag(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.TagConnection, error) {
	return r.Resolver.ListTag(ctx, pagination, orderBy, filter)
}

// AuthorCreated is the resolver for the authorCreated field.
func (r *subscriptionResolver) AuthorCreated(ctx context.Context) (<-chan *model.Author, error) {
	panic(fmt.Errorf("not implemented: AuthorCreated - authorCreated"))
}

// AuthorUpdated is the resolver for the authorUpdated field.
func (r *subscriptionResolver) AuthorUpdated(ctx context.Context) (<-chan *model.Author, error) {
	panic(fmt.Errorf("not implemented: AuthorUpdated - authorUpdated"))
}

// AuthorDeleted is the resolver for the authorDeleted field.
func (r *subscriptionResolver) AuthorDeleted(ctx context.Context) (<-chan *model.Author, error) {
	panic(fmt.Errorf("not implemented: AuthorDeleted - authorDeleted"))
}

// AuthorProfileCreated is the resolver for the authorProfileCreated field.
func (r *subscriptionResolver) AuthorProfileCreated(ctx context.Context) (<-chan *model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: AuthorProfileCreated - authorProfileCreated"))
}

// AuthorProfileUpdated is the resolver for the authorProfileUpdated field.
func (r *subscriptionResolver) AuthorProfileUpdated(ctx context.Context) (<-chan *model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: AuthorProfileUpdated - authorProfileUpdated"))
}

// AuthorProfileDeleted is the resolver for the authorProfileDeleted field.
func (r *subscriptionResolver) AuthorProfileDeleted(ctx context.Context) (<-chan *model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: AuthorProfileDeleted - authorProfileDeleted"))
}

// BookCreated is the resolver for the bookCreated field.
func (r *subscriptionResolver) BookCreated(ctx context.Context) (<-chan *model.Book, error) {
	panic(fmt.Errorf("not implemented: BookCreated - bookCreated"))
}

// BookUpdated is the resolver for the bookUpdated field.
func (r *subscriptionResolver) BookUpdated(ctx context.Context) (<-chan *model.Book, error) {
	panic(fmt.Errorf("not implemented: BookUpdated - bookUpdated"))
}

// BookDeleted is the resolver for the bookDeleted field.
func (r *subscriptionResolver) BookDeleted(ctx context.Context) (<-chan *model.Book, error) {
	panic(fmt.Errorf("not implemented: BookDeleted - bookDeleted"))
}

// ChapterCreated is the resolver for the chapterCreated field.
func (r *subscriptionResolver) ChapterCreated(ctx context.Context) (<-chan *model.Chapter, error) {
	panic(fmt.Errorf("not implemented: ChapterCreated - chapterCreated"))
}

// ChapterUpdated is the resolver for the chapterUpdated field.
func (r *subscriptionResolver) ChapterUpdated(ctx context.Context) (<-chan *model.Chapter, error) {
	panic(fmt.Errorf("not implemented: ChapterUpdated - chapterUpdated"))
}

// ChapterDeleted is the resolver for the chapterDeleted field.
func (r *subscriptionResolver) ChapterDeleted(ctx context.Context) (<-chan *model.Chapter, error) {
	panic(fmt.Errorf("not implemented: ChapterDeleted - chapterDeleted"))
}

// HeadquartersCreated is the resolver for the headquartersCreated field.
func (r *subscriptionResolver) HeadquartersCreated(ctx context.Context) (<-chan *model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: HeadquartersCreated - headquartersCreated"))
}

// HeadquartersUpdated is the resolver for the headquartersUpdated field.
func (r *subscriptionResolver) HeadquartersUpdated(ctx context.Context) (<-chan *model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: HeadquartersUpdated - headquartersUpdated"))
}

// HeadquartersDeleted is the resolver for the headquartersDeleted field.
func (r *subscriptionResolver) HeadquartersDeleted(ctx context.Context) (<-chan *model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: HeadquartersDeleted - headquartersDeleted"))
}

// PublishingHouseCreated is the resolver for the publishingHouseCreated field.
func (r *subscriptionResolver) PublishingHouseCreated(ctx context.Context) (<-chan *model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: PublishingHouseCreated - publishingHouseCreated"))
}

// PublishingHouseUpdated is the resolver for the publishingHouseUpdated field.
func (r *subscriptionResolver) PublishingHouseUpdated(ctx context.Context) (<-chan *model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: PublishingHouseUpdated - publishingHouseUpdated"))
}

// PublishingHouseDeleted is the resolver for the publishingHouseDeleted field.
func (r *subscriptionResolver) PublishingHouseDeleted(ctx context.Context) (<-chan *model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: PublishingHouseDeleted - publishingHouseDeleted"))
}

// TagCreated is the resolver for the tagCreated field.
func (r *subscriptionResolver) TagCreated(ctx context.Context) (<-chan *model.Tag, error) {
	return r.subscribeTag(ctx, tagCreatedTopic)
}

// TagUpdated is the resolver for the tagUpdated field.
func (r *subscriptionResolver) TagUpdated(ctx context.Context) (<-chan *model.Tag, error) {
	return r.subscribeTag(ctx, tagUpdatedTopic)
}

// TagDeleted is the resolver for the tagDeleted field.
func (r *subscriptionResolver) TagDeleted(ctx context.Context) (<-chan *model.Tag, error) {
	return r.subscribeTag(ctx, tagDeletedTopic)
}

// ID is the resolver for the id field.
func (r *tagResolver) ID(ctx context.Context, obj *model.Tag) (model.UUID, error) {
	return asUUID(obj.Id), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *tagResolver) CreatedAt(ctx context.Context, obj *model.Tag) (*model.Time, error) {
	return asTime(obj.CreatedAt), nil
}

// PublisherID is the resolver for the publisherId field.
func (r *createAuthorInputResolver) PublisherID(ctx context.Context, obj *model.CreateAuthorInput, data model.UUID) error {
	setUUID(&obj.PublisherId, data)
	return nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *createAuthorInputResolver) CreatedAt(ctx context.Context, obj *model.CreateAuthorInput, data *model.Time) error {
	setTimePtr(&obj.CreatedAt, data)
	return nil
}

const (
	tagCreatedTopic = "tag:created"
	tagUpdatedTopic = "tag:updated"
	tagDeletedTopic = "tag:deleted"
)

func (r *subscriptionResolver) subscribeTag(ctx context.Context, topic string) (<-chan *model.Tag, error) {
	if r.Events == nil {
		return nil, errors.New("event bus not configured")
	}

	raw, err := r.Events.Subscribe(ctx, topic)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.Tag, 1)
	go func() {
		defer close(out)
		for msg := range raw {
			if msg.Err != nil {
				continue
			}
			switch payload := msg.Payload.(type) {
			case *model.Tag:
				if payload != nil {
					out <- payload
				}
			case model.Tag:
				tag := payload
				out <- &tag
			}
		}
	}()

	return out, nil
}

// HiredAt is the resolver for the hiredAt field.
func (r *createAuthorInputResolver) HiredAt(ctx context.Context, obj *model.CreateAuthorInput, data *model.Time) error {
	setTimePtr(&obj.HiredAt, data)
	return nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *createAuthorInputResolver) UpdatedAt(ctx context.Context, obj *model.CreateAuthorInput, data *model.Time) error {
	setTimePtr(&obj.UpdatedAt, data)
	return nil
}

// AuthorID is the resolver for the authorId field.
func (r *createAuthorProfileInputResolver) AuthorID(ctx context.Context, obj *model.CreateAuthorProfileInput, data model.UUID) error {
	setUUID(&obj.AuthorId, data)
	return nil
}

// AuthorID is the resolver for the authorId field.
func (r *createBookInputResolver) AuthorID(ctx context.Context, obj *model.CreateBookInput, data model.UUID) error {
	setUUID(&obj.AuthorId, data)
	return nil
}

// PublisherID is the resolver for the publisherId field.
func (r *createBookInputResolver) PublisherID(ctx context.Context, obj *model.CreateBookInput, data model.UUID) error {
	setUUID(&obj.PublisherId, data)
	return nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *createBookInputResolver) CreatedAt(ctx context.Context, obj *model.CreateBookInput, data *model.Time) error {
	setTimePtr(&obj.CreatedAt, data)
	return nil
}

// LastReprintAt is the resolver for the lastReprintAt field.
func (r *createBookInputResolver) LastReprintAt(ctx context.Context, obj *model.CreateBookInput, data *model.Time) error {
	setTimePtr(&obj.LastReprintAt, data)
	return nil
}

// ReleaseDate is the resolver for the releaseDate field.
func (r *createBookInputResolver) ReleaseDate(ctx context.Context, obj *model.CreateBookInput, data *model.Time) error {
	setTimePtr(&obj.ReleaseDate, data)
	return nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *createBookInputResolver) UpdatedAt(ctx context.Context, obj *model.CreateBookInput, data *model.Time) error {
	setTimePtr(&obj.UpdatedAt, data)
	return nil
}

// BookID is the resolver for the bookId field.
func (r *createChapterInputResolver) BookID(ctx context.Context, obj *model.CreateChapterInput, data model.UUID) error {
	setUUID(&obj.BookId, data)
	return nil
}

// PublisherID is the resolver for the publisherId field.
func (r *createHeadquartersInputResolver) PublisherID(ctx context.Context, obj *model.CreateHeadquartersInput, data model.UUID) error {
	setUUID(&obj.PublisherId, data)
	return nil
}

// OpenedAt is the resolver for the openedAt field.
func (r *createHeadquartersInputResolver) OpenedAt(ctx context.Context, obj *model.CreateHeadquartersInput, data *model.Time) error {
	setTimePtr(&obj.OpenedAt, data)
	return nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *createPublishingHouseInputResolver) CreatedAt(ctx context.Context, obj *model.CreatePublishingHouseInput, data *model.Time) error {
	setTimePtr(&obj.CreatedAt, data)
	return nil
}

// EstablishedAt is the resolver for the establishedAt field.
func (r *createPublishingHouseInputResolver) EstablishedAt(ctx context.Context, obj *model.CreatePublishingHouseInput, data *model.Time) error {
	setTimePtr(&obj.EstablishedAt, data)
	return nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *createPublishingHouseInputResolver) UpdatedAt(ctx context.Context, obj *model.CreatePublishingHouseInput, data *model.Time) error {
	setTimePtr(&obj.UpdatedAt, data)
	return nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *createTagInputResolver) CreatedAt(ctx context.Context, obj *model.CreateTagInput, data *model.Time) error {
	setTimePtr(&obj.CreatedAt, data)
	return nil
}

// PublisherID is the resolver for the publisherId field.
func (r *updateAuthorInputResolver) PublisherID(ctx context.Context, obj *model.UpdateAuthorInput, data *model.UUID) error {
	setUUIDPtr(&obj.PublisherId, data)
	return nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *updateAuthorInputResolver) CreatedAt(ctx context.Context, obj *model.UpdateAuthorInput, data *model.Time) error {
	setTimePtr(&obj.CreatedAt, data)
	return nil
}

// HiredAt is the resolver for the hiredAt field.
func (r *updateAuthorInputResolver) HiredAt(ctx context.Context, obj *model.UpdateAuthorInput, data *model.Time) error {
	setTimePtr(&obj.HiredAt, data)
	return nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *updateAuthorInputResolver) UpdatedAt(ctx context.Context, obj *model.UpdateAuthorInput, data *model.Time) error {
	setTimePtr(&obj.UpdatedAt, data)
	return nil
}

// AuthorID is the resolver for the authorId field.
func (r *updateAuthorProfileInputResolver) AuthorID(ctx context.Context, obj *model.UpdateAuthorProfileInput, data *model.UUID) error {
	setUUIDPtr(&obj.AuthorId, data)
	return nil
}

// AuthorID is the resolver for the authorId field.
func (r *updateBookInputResolver) AuthorID(ctx context.Context, obj *model.UpdateBookInput, data *model.UUID) error {
	setUUIDPtr(&obj.AuthorId, data)
	return nil
}

// PublisherID is the resolver for the publisherId field.
func (r *updateBookInputResolver) PublisherID(ctx context.Context, obj *model.UpdateBookInput, data *model.UUID) error {
	setUUIDPtr(&obj.PublisherId, data)
	return nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *updateBookInputResolver) CreatedAt(ctx context.Context, obj *model.UpdateBookInput, data *model.Time) error {
	setTimePtr(&obj.CreatedAt, data)
	return nil
}

// LastReprintAt is the resolver for the lastReprintAt field.
func (r *updateBookInputResolver) LastReprintAt(ctx context.Context, obj *model.UpdateBookInput, data *model.Time) error {
	setTimePtr(&obj.LastReprintAt, data)
	return nil
}

// ReleaseDate is the resolver for the releaseDate field.
func (r *updateBookInputResolver) ReleaseDate(ctx context.Context, obj *model.UpdateBookInput, data *model.Time) error {
	setTimePtr(&obj.ReleaseDate, data)
	return nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *updateBookInputResolver) UpdatedAt(ctx context.Context, obj *model.UpdateBookInput, data *model.Time) error {
	setTimePtr(&obj.UpdatedAt, data)
	return nil
}

// BookID is the resolver for the bookId field.
func (r *updateChapterInputResolver) BookID(ctx context.Context, obj *model.UpdateChapterInput, data *model.UUID) error {
	setUUIDPtr(&obj.BookId, data)
	return nil
}

// PublisherID is the resolver for the publisherId field.
func (r *updateHeadquartersInputResolver) PublisherID(ctx context.Context, obj *model.UpdateHeadquartersInput, data *model.UUID) error {
	setUUIDPtr(&obj.PublisherId, data)
	return nil
}

// OpenedAt is the resolver for the openedAt field.
func (r *updateHeadquartersInputResolver) OpenedAt(ctx context.Context, obj *model.UpdateHeadquartersInput, data *model.Time) error {
	setTimePtr(&obj.OpenedAt, data)
	return nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *updatePublishingHouseInputResolver) CreatedAt(ctx context.Context, obj *model.UpdatePublishingHouseInput, data *model.Time) error {
	setTimePtr(&obj.CreatedAt, data)
	return nil
}

// EstablishedAt is the resolver for the establishedAt field.
func (r *updatePublishingHouseInputResolver) EstablishedAt(ctx context.Context, obj *model.UpdatePublishingHouseInput, data *model.Time) error {
	setTimePtr(&obj.EstablishedAt, data)
	return nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *updatePublishingHouseInputResolver) UpdatedAt(ctx context.Context, obj *model.UpdatePublishingHouseInput, data *model.Time) error {
	setTimePtr(&obj.UpdatedAt, data)
	return nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *updateTagInputResolver) CreatedAt(ctx context.Context, obj *model.UpdateTagInput, data *model.Time) error {
	setTimePtr(&obj.CreatedAt, data)
	return nil
}

// Author returns generated.AuthorResolver implementation.
func (r *Resolver) Author() generated.AuthorResolver { return &authorResolver{r} }

// AuthorProfile returns generated.AuthorProfileResolver implementation.
func (r *Resolver) AuthorProfile() generated.AuthorProfileResolver { return &authorProfileResolver{r} }

// Book returns generated.BookResolver implementation.
func (r *Resolver) Book() generated.BookResolver { return &bookResolver{r} }

// Chapter returns generated.ChapterResolver implementation.
func (r *Resolver) Chapter() generated.ChapterResolver { return &chapterResolver{r} }

// Headquarters returns generated.HeadquartersResolver implementation.
func (r *Resolver) Headquarters() generated.HeadquartersResolver { return &headquartersResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// PublishingHouse returns generated.PublishingHouseResolver implementation.
func (r *Resolver) PublishingHouse() generated.PublishingHouseResolver {
	return &publishingHouseResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// Tag returns generated.TagResolver implementation.
func (r *Resolver) Tag() generated.TagResolver { return &tagResolver{r} }

// CreateAuthorInput returns generated.CreateAuthorInputResolver implementation.
func (r *Resolver) CreateAuthorInput() generated.CreateAuthorInputResolver {
	return &createAuthorInputResolver{r}
}

// CreateAuthorProfileInput returns generated.CreateAuthorProfileInputResolver implementation.
func (r *Resolver) CreateAuthorProfileInput() generated.CreateAuthorProfileInputResolver {
	return &createAuthorProfileInputResolver{r}
}

// CreateBookInput returns generated.CreateBookInputResolver implementation.
func (r *Resolver) CreateBookInput() generated.CreateBookInputResolver {
	return &createBookInputResolver{r}
}

// CreateChapterInput returns generated.CreateChapterInputResolver implementation.
func (r *Resolver) CreateChapterInput() generated.CreateChapterInputResolver {
	return &createChapterInputResolver{r}
}

// CreateHeadquartersInput returns generated.CreateHeadquartersInputResolver implementation.
func (r *Resolver) CreateHeadquartersInput() generated.CreateHeadquartersInputResolver {
	return &createHeadquartersInputResolver{r}
}

// CreatePublishingHouseInput returns generated.CreatePublishingHouseInputResolver implementation.
func (r *Resolver) CreatePublishingHouseInput() generated.CreatePublishingHouseInputResolver {
	return &createPublishingHouseInputResolver{r}
}

// CreateTagInput returns generated.CreateTagInputResolver implementation.
func (r *Resolver) CreateTagInput() generated.CreateTagInputResolver {
	return &createTagInputResolver{r}
}

// UpdateAuthorInput returns generated.UpdateAuthorInputResolver implementation.
func (r *Resolver) UpdateAuthorInput() generated.UpdateAuthorInputResolver {
	return &updateAuthorInputResolver{r}
}

// UpdateAuthorProfileInput returns generated.UpdateAuthorProfileInputResolver implementation.
func (r *Resolver) UpdateAuthorProfileInput() generated.UpdateAuthorProfileInputResolver {
	return &updateAuthorProfileInputResolver{r}
}

// UpdateBookInput returns generated.UpdateBookInputResolver implementation.
func (r *Resolver) UpdateBookInput() generated.UpdateBookInputResolver {
	return &updateBookInputResolver{r}
}

// UpdateChapterInput returns generated.UpdateChapterInputResolver implementation.
func (r *Resolver) UpdateChapterInput() generated.UpdateChapterInputResolver {
	return &updateChapterInputResolver{r}
}

// UpdateHeadquartersInput returns generated.UpdateHeadquartersInputResolver implementation.
func (r *Resolver) UpdateHeadquartersInput() generated.UpdateHeadquartersInputResolver {
	return &updateHeadquartersInputResolver{r}
}

// UpdatePublishingHouseInput returns generated.UpdatePublishingHouseInputResolver implementation.
func (r *Resolver) UpdatePublishingHouseInput() generated.UpdatePublishingHouseInputResolver {
	return &updatePublishingHouseInputResolver{r}
}

// UpdateTagInput returns generated.UpdateTagInputResolver implementation.
func (r *Resolver) UpdateTagInput() generated.UpdateTagInputResolver {
	return &updateTagInputResolver{r}
}

type authorResolver struct{ *Resolver }
type authorProfileResolver struct{ *Resolver }
type bookResolver struct{ *Resolver }
type chapterResolver struct{ *Resolver }
type headquartersResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type publishingHouseResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tagResolver struct{ *Resolver }
type createAuthorInputResolver struct{ *Resolver }
type createAuthorProfileInputResolver struct{ *Resolver }
type createBookInputResolver struct{ *Resolver }
type createChapterInputResolver struct{ *Resolver }
type createHeadquartersInputResolver struct{ *Resolver }
type createPublishingHouseInputResolver struct{ *Resolver }
type createTagInputResolver struct{ *Resolver }
type updateAuthorInputResolver struct{ *Resolver }
type updateAuthorProfileInputResolver struct{ *Resolver }
type updateBookInputResolver struct{ *Resolver }
type updateChapterInputResolver struct{ *Resolver }
type updateHeadquartersInputResolver struct{ *Resolver }
type updatePublishingHouseInputResolver struct{ *Resolver }
type updateTagInputResolver struct{ *Resolver }
