package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/goliatone/go-crud/examples/relationships-gql/graph/generated"
	"github.com/goliatone/go-crud/examples/relationships-gql/graph/model"
)

// ID is the resolver for the id field.
func (r *authorResolver) ID(ctx context.Context, obj *model.Author) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *authorResolver) CreatedAt(ctx context.Context, obj *model.Author) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *authorResolver) UpdatedAt(ctx context.Context, obj *model.Author) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// HiredAt is the resolver for the hiredAt field.
func (r *authorResolver) HiredAt(ctx context.Context, obj *model.Author) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: HiredAt - hiredAt"))
}

// PublisherID is the resolver for the publisherId field.
func (r *authorResolver) PublisherID(ctx context.Context, obj *model.Author) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// ID is the resolver for the id field.
func (r *authorProfileResolver) ID(ctx context.Context, obj *model.AuthorProfile) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// AuthorID is the resolver for the authorId field.
func (r *authorProfileResolver) AuthorID(ctx context.Context, obj *model.AuthorProfile) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: AuthorID - authorId"))
}

// ID is the resolver for the id field.
func (r *bookResolver) ID(ctx context.Context, obj *model.Book) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *bookResolver) CreatedAt(ctx context.Context, obj *model.Book) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *bookResolver) UpdatedAt(ctx context.Context, obj *model.Book) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// AuthorID is the resolver for the authorId field.
func (r *bookResolver) AuthorID(ctx context.Context, obj *model.Book) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: AuthorID - authorId"))
}

// LastReprintAt is the resolver for the lastReprintAt field.
func (r *bookResolver) LastReprintAt(ctx context.Context, obj *model.Book) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: LastReprintAt - lastReprintAt"))
}

// PublisherID is the resolver for the publisherId field.
func (r *bookResolver) PublisherID(ctx context.Context, obj *model.Book) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// ReleaseDate is the resolver for the releaseDate field.
func (r *bookResolver) ReleaseDate(ctx context.Context, obj *model.Book) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: ReleaseDate - releaseDate"))
}

// ID is the resolver for the id field.
func (r *chapterResolver) ID(ctx context.Context, obj *model.Chapter) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// BookID is the resolver for the bookId field.
func (r *chapterResolver) BookID(ctx context.Context, obj *model.Chapter) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: BookID - bookId"))
}

// ID is the resolver for the id field.
func (r *headquartersResolver) ID(ctx context.Context, obj *model.Headquarters) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// OpenedAt is the resolver for the openedAt field.
func (r *headquartersResolver) OpenedAt(ctx context.Context, obj *model.Headquarters) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: OpenedAt - openedAt"))
}

// PublisherID is the resolver for the publisherId field.
func (r *headquartersResolver) PublisherID(ctx context.Context, obj *model.Headquarters) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input model.CreateAuthorInput) (*model.Author, error) {
	panic(fmt.Errorf("not implemented: CreateAuthor - createAuthor"))
}

// UpdateAuthor is the resolver for the updateAuthor field.
func (r *mutationResolver) UpdateAuthor(ctx context.Context, id model.UUID, input model.UpdateAuthorInput) (*model.Author, error) {
	panic(fmt.Errorf("not implemented: UpdateAuthor - updateAuthor"))
}

// DeleteAuthor is the resolver for the deleteAuthor field.
func (r *mutationResolver) DeleteAuthor(ctx context.Context, id model.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAuthor - deleteAuthor"))
}

// CreateAuthorProfile is the resolver for the createAuthorProfile field.
func (r *mutationResolver) CreateAuthorProfile(ctx context.Context, input model.CreateAuthorProfileInput) (*model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: CreateAuthorProfile - createAuthorProfile"))
}

// UpdateAuthorProfile is the resolver for the updateAuthorProfile field.
func (r *mutationResolver) UpdateAuthorProfile(ctx context.Context, id model.UUID, input model.UpdateAuthorProfileInput) (*model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: UpdateAuthorProfile - updateAuthorProfile"))
}

// DeleteAuthorProfile is the resolver for the deleteAuthorProfile field.
func (r *mutationResolver) DeleteAuthorProfile(ctx context.Context, id model.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAuthorProfile - deleteAuthorProfile"))
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.CreateBookInput) (*model.Book, error) {
	panic(fmt.Errorf("not implemented: CreateBook - createBook"))
}

// UpdateBook is the resolver for the updateBook field.
func (r *mutationResolver) UpdateBook(ctx context.Context, id model.UUID, input model.UpdateBookInput) (*model.Book, error) {
	panic(fmt.Errorf("not implemented: UpdateBook - updateBook"))
}

// DeleteBook is the resolver for the deleteBook field.
func (r *mutationResolver) DeleteBook(ctx context.Context, id model.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteBook - deleteBook"))
}

// CreateChapter is the resolver for the createChapter field.
func (r *mutationResolver) CreateChapter(ctx context.Context, input model.CreateChapterInput) (*model.Chapter, error) {
	panic(fmt.Errorf("not implemented: CreateChapter - createChapter"))
}

// UpdateChapter is the resolver for the updateChapter field.
func (r *mutationResolver) UpdateChapter(ctx context.Context, id model.UUID, input model.UpdateChapterInput) (*model.Chapter, error) {
	panic(fmt.Errorf("not implemented: UpdateChapter - updateChapter"))
}

// DeleteChapter is the resolver for the deleteChapter field.
func (r *mutationResolver) DeleteChapter(ctx context.Context, id model.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteChapter - deleteChapter"))
}

// CreateHeadquarters is the resolver for the createHeadquarters field.
func (r *mutationResolver) CreateHeadquarters(ctx context.Context, input model.CreateHeadquartersInput) (*model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: CreateHeadquarters - createHeadquarters"))
}

// UpdateHeadquarters is the resolver for the updateHeadquarters field.
func (r *mutationResolver) UpdateHeadquarters(ctx context.Context, id model.UUID, input model.UpdateHeadquartersInput) (*model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: UpdateHeadquarters - updateHeadquarters"))
}

// DeleteHeadquarters is the resolver for the deleteHeadquarters field.
func (r *mutationResolver) DeleteHeadquarters(ctx context.Context, id model.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteHeadquarters - deleteHeadquarters"))
}

// CreatePublishingHouse is the resolver for the createPublishingHouse field.
func (r *mutationResolver) CreatePublishingHouse(ctx context.Context, input model.CreatePublishingHouseInput) (*model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: CreatePublishingHouse - createPublishingHouse"))
}

// UpdatePublishingHouse is the resolver for the updatePublishingHouse field.
func (r *mutationResolver) UpdatePublishingHouse(ctx context.Context, id model.UUID, input model.UpdatePublishingHouseInput) (*model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: UpdatePublishingHouse - updatePublishingHouse"))
}

// DeletePublishingHouse is the resolver for the deletePublishingHouse field.
func (r *mutationResolver) DeletePublishingHouse(ctx context.Context, id model.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeletePublishingHouse - deletePublishingHouse"))
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.Tag, error) {
	panic(fmt.Errorf("not implemented: CreateTag - createTag"))
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, id model.UUID, input model.UpdateTagInput) (*model.Tag, error) {
	panic(fmt.Errorf("not implemented: UpdateTag - updateTag"))
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id model.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTag - deleteTag"))
}

// ID is the resolver for the id field.
func (r *publishingHouseResolver) ID(ctx context.Context, obj *model.PublishingHouse) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *publishingHouseResolver) CreatedAt(ctx context.Context, obj *model.PublishingHouse) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *publishingHouseResolver) UpdatedAt(ctx context.Context, obj *model.PublishingHouse) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// EstablishedAt is the resolver for the establishedAt field.
func (r *publishingHouseResolver) EstablishedAt(ctx context.Context, obj *model.PublishingHouse) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: EstablishedAt - establishedAt"))
}

// GetAuthor is the resolver for the getAuthor field.
func (r *queryResolver) GetAuthor(ctx context.Context, id model.UUID) (*model.Author, error) {
	panic(fmt.Errorf("not implemented: GetAuthor - getAuthor"))
}

// ListAuthor is the resolver for the listAuthor field.
func (r *queryResolver) ListAuthor(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.AuthorConnection, error) {
	panic(fmt.Errorf("not implemented: ListAuthor - listAuthor"))
}

// GetAuthorProfile is the resolver for the getAuthorProfile field.
func (r *queryResolver) GetAuthorProfile(ctx context.Context, id model.UUID) (*model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: GetAuthorProfile - getAuthorProfile"))
}

// ListAuthorProfile is the resolver for the listAuthorProfile field.
func (r *queryResolver) ListAuthorProfile(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.AuthorProfileConnection, error) {
	panic(fmt.Errorf("not implemented: ListAuthorProfile - listAuthorProfile"))
}

// GetBook is the resolver for the getBook field.
func (r *queryResolver) GetBook(ctx context.Context, id model.UUID) (*model.Book, error) {
	panic(fmt.Errorf("not implemented: GetBook - getBook"))
}

// ListBook is the resolver for the listBook field.
func (r *queryResolver) ListBook(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.BookConnection, error) {
	panic(fmt.Errorf("not implemented: ListBook - listBook"))
}

// GetChapter is the resolver for the getChapter field.
func (r *queryResolver) GetChapter(ctx context.Context, id model.UUID) (*model.Chapter, error) {
	panic(fmt.Errorf("not implemented: GetChapter - getChapter"))
}

// ListChapter is the resolver for the listChapter field.
func (r *queryResolver) ListChapter(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.ChapterConnection, error) {
	panic(fmt.Errorf("not implemented: ListChapter - listChapter"))
}

// GetHeadquarters is the resolver for the getHeadquarters field.
func (r *queryResolver) GetHeadquarters(ctx context.Context, id model.UUID) (*model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: GetHeadquarters - getHeadquarters"))
}

// ListHeadquarters is the resolver for the listHeadquarters field.
func (r *queryResolver) ListHeadquarters(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.HeadquartersConnection, error) {
	panic(fmt.Errorf("not implemented: ListHeadquarters - listHeadquarters"))
}

// GetPublishingHouse is the resolver for the getPublishingHouse field.
func (r *queryResolver) GetPublishingHouse(ctx context.Context, id model.UUID) (*model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: GetPublishingHouse - getPublishingHouse"))
}

// ListPublishingHouse is the resolver for the listPublishingHouse field.
func (r *queryResolver) ListPublishingHouse(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.PublishingHouseConnection, error) {
	panic(fmt.Errorf("not implemented: ListPublishingHouse - listPublishingHouse"))
}

// GetTag is the resolver for the getTag field.
func (r *queryResolver) GetTag(ctx context.Context, id model.UUID) (*model.Tag, error) {
	panic(fmt.Errorf("not implemented: GetTag - getTag"))
}

// ListTag is the resolver for the listTag field.
func (r *queryResolver) ListTag(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.TagConnection, error) {
	panic(fmt.Errorf("not implemented: ListTag - listTag"))
}

// AuthorCreated is the resolver for the authorCreated field.
func (r *subscriptionResolver) AuthorCreated(ctx context.Context) (<-chan *model.Author, error) {
	panic(fmt.Errorf("not implemented: AuthorCreated - authorCreated"))
}

// AuthorUpdated is the resolver for the authorUpdated field.
func (r *subscriptionResolver) AuthorUpdated(ctx context.Context) (<-chan *model.Author, error) {
	panic(fmt.Errorf("not implemented: AuthorUpdated - authorUpdated"))
}

// AuthorDeleted is the resolver for the authorDeleted field.
func (r *subscriptionResolver) AuthorDeleted(ctx context.Context) (<-chan *model.Author, error) {
	panic(fmt.Errorf("not implemented: AuthorDeleted - authorDeleted"))
}

// AuthorProfileCreated is the resolver for the authorProfileCreated field.
func (r *subscriptionResolver) AuthorProfileCreated(ctx context.Context) (<-chan *model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: AuthorProfileCreated - authorProfileCreated"))
}

// AuthorProfileUpdated is the resolver for the authorProfileUpdated field.
func (r *subscriptionResolver) AuthorProfileUpdated(ctx context.Context) (<-chan *model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: AuthorProfileUpdated - authorProfileUpdated"))
}

// AuthorProfileDeleted is the resolver for the authorProfileDeleted field.
func (r *subscriptionResolver) AuthorProfileDeleted(ctx context.Context) (<-chan *model.AuthorProfile, error) {
	panic(fmt.Errorf("not implemented: AuthorProfileDeleted - authorProfileDeleted"))
}

// BookCreated is the resolver for the bookCreated field.
func (r *subscriptionResolver) BookCreated(ctx context.Context) (<-chan *model.Book, error) {
	panic(fmt.Errorf("not implemented: BookCreated - bookCreated"))
}

// BookUpdated is the resolver for the bookUpdated field.
func (r *subscriptionResolver) BookUpdated(ctx context.Context) (<-chan *model.Book, error) {
	panic(fmt.Errorf("not implemented: BookUpdated - bookUpdated"))
}

// BookDeleted is the resolver for the bookDeleted field.
func (r *subscriptionResolver) BookDeleted(ctx context.Context) (<-chan *model.Book, error) {
	panic(fmt.Errorf("not implemented: BookDeleted - bookDeleted"))
}

// ChapterCreated is the resolver for the chapterCreated field.
func (r *subscriptionResolver) ChapterCreated(ctx context.Context) (<-chan *model.Chapter, error) {
	panic(fmt.Errorf("not implemented: ChapterCreated - chapterCreated"))
}

// ChapterUpdated is the resolver for the chapterUpdated field.
func (r *subscriptionResolver) ChapterUpdated(ctx context.Context) (<-chan *model.Chapter, error) {
	panic(fmt.Errorf("not implemented: ChapterUpdated - chapterUpdated"))
}

// ChapterDeleted is the resolver for the chapterDeleted field.
func (r *subscriptionResolver) ChapterDeleted(ctx context.Context) (<-chan *model.Chapter, error) {
	panic(fmt.Errorf("not implemented: ChapterDeleted - chapterDeleted"))
}

// HeadquartersCreated is the resolver for the headquartersCreated field.
func (r *subscriptionResolver) HeadquartersCreated(ctx context.Context) (<-chan *model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: HeadquartersCreated - headquartersCreated"))
}

// HeadquartersUpdated is the resolver for the headquartersUpdated field.
func (r *subscriptionResolver) HeadquartersUpdated(ctx context.Context) (<-chan *model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: HeadquartersUpdated - headquartersUpdated"))
}

// HeadquartersDeleted is the resolver for the headquartersDeleted field.
func (r *subscriptionResolver) HeadquartersDeleted(ctx context.Context) (<-chan *model.Headquarters, error) {
	panic(fmt.Errorf("not implemented: HeadquartersDeleted - headquartersDeleted"))
}

// PublishingHouseCreated is the resolver for the publishingHouseCreated field.
func (r *subscriptionResolver) PublishingHouseCreated(ctx context.Context) (<-chan *model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: PublishingHouseCreated - publishingHouseCreated"))
}

// PublishingHouseUpdated is the resolver for the publishingHouseUpdated field.
func (r *subscriptionResolver) PublishingHouseUpdated(ctx context.Context) (<-chan *model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: PublishingHouseUpdated - publishingHouseUpdated"))
}

// PublishingHouseDeleted is the resolver for the publishingHouseDeleted field.
func (r *subscriptionResolver) PublishingHouseDeleted(ctx context.Context) (<-chan *model.PublishingHouse, error) {
	panic(fmt.Errorf("not implemented: PublishingHouseDeleted - publishingHouseDeleted"))
}

// TagCreated is the resolver for the tagCreated field.
func (r *subscriptionResolver) TagCreated(ctx context.Context) (<-chan *model.Tag, error) {
	panic(fmt.Errorf("not implemented: TagCreated - tagCreated"))
}

// TagUpdated is the resolver for the tagUpdated field.
func (r *subscriptionResolver) TagUpdated(ctx context.Context) (<-chan *model.Tag, error) {
	panic(fmt.Errorf("not implemented: TagUpdated - tagUpdated"))
}

// TagDeleted is the resolver for the tagDeleted field.
func (r *subscriptionResolver) TagDeleted(ctx context.Context) (<-chan *model.Tag, error) {
	panic(fmt.Errorf("not implemented: TagDeleted - tagDeleted"))
}

// ID is the resolver for the id field.
func (r *tagResolver) ID(ctx context.Context, obj *model.Tag) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *tagResolver) CreatedAt(ctx context.Context, obj *model.Tag) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// PublisherID is the resolver for the publisherId field.
func (r *createAuthorInputResolver) PublisherID(ctx context.Context, obj *model.CreateAuthorInput, data model.UUID) error {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *createAuthorInputResolver) CreatedAt(ctx context.Context, obj *model.CreateAuthorInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// HiredAt is the resolver for the hiredAt field.
func (r *createAuthorInputResolver) HiredAt(ctx context.Context, obj *model.CreateAuthorInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: HiredAt - hiredAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *createAuthorInputResolver) UpdatedAt(ctx context.Context, obj *model.CreateAuthorInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// AuthorID is the resolver for the authorId field.
func (r *createAuthorProfileInputResolver) AuthorID(ctx context.Context, obj *model.CreateAuthorProfileInput, data model.UUID) error {
	panic(fmt.Errorf("not implemented: AuthorID - authorId"))
}

// AuthorID is the resolver for the authorId field.
func (r *createBookInputResolver) AuthorID(ctx context.Context, obj *model.CreateBookInput, data model.UUID) error {
	panic(fmt.Errorf("not implemented: AuthorID - authorId"))
}

// PublisherID is the resolver for the publisherId field.
func (r *createBookInputResolver) PublisherID(ctx context.Context, obj *model.CreateBookInput, data model.UUID) error {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *createBookInputResolver) CreatedAt(ctx context.Context, obj *model.CreateBookInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// LastReprintAt is the resolver for the lastReprintAt field.
func (r *createBookInputResolver) LastReprintAt(ctx context.Context, obj *model.CreateBookInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: LastReprintAt - lastReprintAt"))
}

// ReleaseDate is the resolver for the releaseDate field.
func (r *createBookInputResolver) ReleaseDate(ctx context.Context, obj *model.CreateBookInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: ReleaseDate - releaseDate"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *createBookInputResolver) UpdatedAt(ctx context.Context, obj *model.CreateBookInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// BookID is the resolver for the bookId field.
func (r *createChapterInputResolver) BookID(ctx context.Context, obj *model.CreateChapterInput, data model.UUID) error {
	panic(fmt.Errorf("not implemented: BookID - bookId"))
}

// PublisherID is the resolver for the publisherId field.
func (r *createHeadquartersInputResolver) PublisherID(ctx context.Context, obj *model.CreateHeadquartersInput, data model.UUID) error {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// OpenedAt is the resolver for the openedAt field.
func (r *createHeadquartersInputResolver) OpenedAt(ctx context.Context, obj *model.CreateHeadquartersInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: OpenedAt - openedAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *createPublishingHouseInputResolver) CreatedAt(ctx context.Context, obj *model.CreatePublishingHouseInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// EstablishedAt is the resolver for the establishedAt field.
func (r *createPublishingHouseInputResolver) EstablishedAt(ctx context.Context, obj *model.CreatePublishingHouseInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: EstablishedAt - establishedAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *createPublishingHouseInputResolver) UpdatedAt(ctx context.Context, obj *model.CreatePublishingHouseInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *createTagInputResolver) CreatedAt(ctx context.Context, obj *model.CreateTagInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// PublisherID is the resolver for the publisherId field.
func (r *updateAuthorInputResolver) PublisherID(ctx context.Context, obj *model.UpdateAuthorInput, data *model.UUID) error {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *updateAuthorInputResolver) CreatedAt(ctx context.Context, obj *model.UpdateAuthorInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// HiredAt is the resolver for the hiredAt field.
func (r *updateAuthorInputResolver) HiredAt(ctx context.Context, obj *model.UpdateAuthorInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: HiredAt - hiredAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *updateAuthorInputResolver) UpdatedAt(ctx context.Context, obj *model.UpdateAuthorInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// AuthorID is the resolver for the authorId field.
func (r *updateAuthorProfileInputResolver) AuthorID(ctx context.Context, obj *model.UpdateAuthorProfileInput, data *model.UUID) error {
	panic(fmt.Errorf("not implemented: AuthorID - authorId"))
}

// AuthorID is the resolver for the authorId field.
func (r *updateBookInputResolver) AuthorID(ctx context.Context, obj *model.UpdateBookInput, data *model.UUID) error {
	panic(fmt.Errorf("not implemented: AuthorID - authorId"))
}

// PublisherID is the resolver for the publisherId field.
func (r *updateBookInputResolver) PublisherID(ctx context.Context, obj *model.UpdateBookInput, data *model.UUID) error {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *updateBookInputResolver) CreatedAt(ctx context.Context, obj *model.UpdateBookInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// LastReprintAt is the resolver for the lastReprintAt field.
func (r *updateBookInputResolver) LastReprintAt(ctx context.Context, obj *model.UpdateBookInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: LastReprintAt - lastReprintAt"))
}

// ReleaseDate is the resolver for the releaseDate field.
func (r *updateBookInputResolver) ReleaseDate(ctx context.Context, obj *model.UpdateBookInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: ReleaseDate - releaseDate"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *updateBookInputResolver) UpdatedAt(ctx context.Context, obj *model.UpdateBookInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// BookID is the resolver for the bookId field.
func (r *updateChapterInputResolver) BookID(ctx context.Context, obj *model.UpdateChapterInput, data *model.UUID) error {
	panic(fmt.Errorf("not implemented: BookID - bookId"))
}

// PublisherID is the resolver for the publisherId field.
func (r *updateHeadquartersInputResolver) PublisherID(ctx context.Context, obj *model.UpdateHeadquartersInput, data *model.UUID) error {
	panic(fmt.Errorf("not implemented: PublisherID - publisherId"))
}

// OpenedAt is the resolver for the openedAt field.
func (r *updateHeadquartersInputResolver) OpenedAt(ctx context.Context, obj *model.UpdateHeadquartersInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: OpenedAt - openedAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *updatePublishingHouseInputResolver) CreatedAt(ctx context.Context, obj *model.UpdatePublishingHouseInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// EstablishedAt is the resolver for the establishedAt field.
func (r *updatePublishingHouseInputResolver) EstablishedAt(ctx context.Context, obj *model.UpdatePublishingHouseInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: EstablishedAt - establishedAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *updatePublishingHouseInputResolver) UpdatedAt(ctx context.Context, obj *model.UpdatePublishingHouseInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *updateTagInputResolver) CreatedAt(ctx context.Context, obj *model.UpdateTagInput, data *model.Time) error {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// Author returns generated.AuthorResolver implementation.
func (r *Resolver) Author() generated.AuthorResolver { return &authorResolver{r} }

// AuthorProfile returns generated.AuthorProfileResolver implementation.
func (r *Resolver) AuthorProfile() generated.AuthorProfileResolver { return &authorProfileResolver{r} }

// Book returns generated.BookResolver implementation.
func (r *Resolver) Book() generated.BookResolver { return &bookResolver{r} }

// Chapter returns generated.ChapterResolver implementation.
func (r *Resolver) Chapter() generated.ChapterResolver { return &chapterResolver{r} }

// Headquarters returns generated.HeadquartersResolver implementation.
func (r *Resolver) Headquarters() generated.HeadquartersResolver { return &headquartersResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// PublishingHouse returns generated.PublishingHouseResolver implementation.
func (r *Resolver) PublishingHouse() generated.PublishingHouseResolver {
	return &publishingHouseResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// Tag returns generated.TagResolver implementation.
func (r *Resolver) Tag() generated.TagResolver { return &tagResolver{r} }

// CreateAuthorInput returns generated.CreateAuthorInputResolver implementation.
func (r *Resolver) CreateAuthorInput() generated.CreateAuthorInputResolver {
	return &createAuthorInputResolver{r}
}

// CreateAuthorProfileInput returns generated.CreateAuthorProfileInputResolver implementation.
func (r *Resolver) CreateAuthorProfileInput() generated.CreateAuthorProfileInputResolver {
	return &createAuthorProfileInputResolver{r}
}

// CreateBookInput returns generated.CreateBookInputResolver implementation.
func (r *Resolver) CreateBookInput() generated.CreateBookInputResolver {
	return &createBookInputResolver{r}
}

// CreateChapterInput returns generated.CreateChapterInputResolver implementation.
func (r *Resolver) CreateChapterInput() generated.CreateChapterInputResolver {
	return &createChapterInputResolver{r}
}

// CreateHeadquartersInput returns generated.CreateHeadquartersInputResolver implementation.
func (r *Resolver) CreateHeadquartersInput() generated.CreateHeadquartersInputResolver {
	return &createHeadquartersInputResolver{r}
}

// CreatePublishingHouseInput returns generated.CreatePublishingHouseInputResolver implementation.
func (r *Resolver) CreatePublishingHouseInput() generated.CreatePublishingHouseInputResolver {
	return &createPublishingHouseInputResolver{r}
}

// CreateTagInput returns generated.CreateTagInputResolver implementation.
func (r *Resolver) CreateTagInput() generated.CreateTagInputResolver {
	return &createTagInputResolver{r}
}

// UpdateAuthorInput returns generated.UpdateAuthorInputResolver implementation.
func (r *Resolver) UpdateAuthorInput() generated.UpdateAuthorInputResolver {
	return &updateAuthorInputResolver{r}
}

// UpdateAuthorProfileInput returns generated.UpdateAuthorProfileInputResolver implementation.
func (r *Resolver) UpdateAuthorProfileInput() generated.UpdateAuthorProfileInputResolver {
	return &updateAuthorProfileInputResolver{r}
}

// UpdateBookInput returns generated.UpdateBookInputResolver implementation.
func (r *Resolver) UpdateBookInput() generated.UpdateBookInputResolver {
	return &updateBookInputResolver{r}
}

// UpdateChapterInput returns generated.UpdateChapterInputResolver implementation.
func (r *Resolver) UpdateChapterInput() generated.UpdateChapterInputResolver {
	return &updateChapterInputResolver{r}
}

// UpdateHeadquartersInput returns generated.UpdateHeadquartersInputResolver implementation.
func (r *Resolver) UpdateHeadquartersInput() generated.UpdateHeadquartersInputResolver {
	return &updateHeadquartersInputResolver{r}
}

// UpdatePublishingHouseInput returns generated.UpdatePublishingHouseInputResolver implementation.
func (r *Resolver) UpdatePublishingHouseInput() generated.UpdatePublishingHouseInputResolver {
	return &updatePublishingHouseInputResolver{r}
}

// UpdateTagInput returns generated.UpdateTagInputResolver implementation.
func (r *Resolver) UpdateTagInput() generated.UpdateTagInputResolver {
	return &updateTagInputResolver{r}
}

type authorResolver struct{ *Resolver }
type authorProfileResolver struct{ *Resolver }
type bookResolver struct{ *Resolver }
type chapterResolver struct{ *Resolver }
type headquartersResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type publishingHouseResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tagResolver struct{ *Resolver }
type createAuthorInputResolver struct{ *Resolver }
type createAuthorProfileInputResolver struct{ *Resolver }
type createBookInputResolver struct{ *Resolver }
type createChapterInputResolver struct{ *Resolver }
type createHeadquartersInputResolver struct{ *Resolver }
type createPublishingHouseInputResolver struct{ *Resolver }
type createTagInputResolver struct{ *Resolver }
type updateAuthorInputResolver struct{ *Resolver }
type updateAuthorProfileInputResolver struct{ *Resolver }
type updateBookInputResolver struct{ *Resolver }
type updateChapterInputResolver struct{ *Resolver }
type updateHeadquartersInputResolver struct{ *Resolver }
type updatePublishingHouseInputResolver struct{ *Resolver }
type updateTagInputResolver struct{ *Resolver }
