package resolvers

// Code generated by graphqlgen. DO NOT EDIT.

import (
	"context"
	"encoding/base64"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/goliatone/go-crud"
	repository "github.com/goliatone/go-repository-bun"
	"github.com/uptrace/bun"

	"github.com/goliatone/go-crud/gql/model"
)

type ScopeGuardFunc func(ctx context.Context, entity, action string) error
type ContextFactory func(ctx context.Context) crud.Context

type criteriaField struct {
	Column       string
	Relation     string
	RelationType string
	PivotTable   string
	SourceColumn string
	TargetColumn string
	SourcePivot  string
	TargetPivot  string
	TargetTable  string
}

var criteriaConfig = map[string]map[string]criteriaField{

	"Content": {

		"data":   {Column: "data"},
		"id":     {Column: "id"},
		"locale": {Column: "locale"},
		"slug":   {Column: "slug"},
		"status": {Column: "status"},
		"type":   {Column: "type"},
	},

	"Menu": {

		"code":     {Column: "code"},
		"id":       {Column: "id"},
		"items":    {Column: "items"},
		"location": {Column: "location"},
	},

	"Page": {

		"data":   {Column: "data"},
		"id":     {Column: "id"},
		"locale": {Column: "locale"},
		"slug":   {Column: "slug"},
		"status": {Column: "status"},
		"title":  {Column: "title"},
	},
}

func findOriginalNameForJoinKey(entity, joinKey string) string {
	joinKey = strings.ToLower(strings.TrimSpace(joinKey))
	if joinKey == "" {
		return ""
	}
	base := strings.SplitN(joinKey, ".", 2)[0]
	fields, ok := criteriaConfig[entity]
	if !ok {
		return base
	}
	if field, ok := fields[base]; ok && field.Relation != "" {
		return field.Relation
	}
	for key, field := range fields {
		prefix := strings.SplitN(key, ".", 2)[0]
		if prefix == base && field.Relation != "" {
			return field.Relation
		}
	}
	return base
}

func (r *Resolver) crudContext(ctx context.Context) crud.Context {
	if r.ContextFactory != nil {
		return r.ContextFactory(ctx)
	}
	return nil
}

func (r *Resolver) guard(ctx context.Context, entity, action string) error {
	if r.ScopeGuard != nil {
		if err := r.ScopeGuard(ctx, entity, action); err != nil {
			return err
		}
	}
	return nil
}

func buildCriteria(entity string, p *model.PaginationInput, order []*model.OrderByInput, filters []*model.FilterInput) []repository.SelectCriteria {
	fields := criteriaConfig[entity]
	criteria := make([]repository.SelectCriteria, 0, 1+len(order)+len(filters))

	if p != nil {
		if p.Limit != nil && *p.Limit > 0 {
			limit := *p.Limit
			criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
				return q.Limit(limit)
			})
		}
		if p.Offset != nil && *p.Offset >= 0 {
			offset := *p.Offset
			criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
				return q.Offset(offset)
			})
		}
	}

	for _, ob := range order {
		if ob == nil || ob.Field == "" {
			continue
		}
		field, ok := lookupField(fields, ob.Field)
		if !ok {
			continue
		}

		dir := normalizeDirection(ob.Direction)
		column := field.Column
		relation := findOriginalNameForJoinKey(entity, ob.Field)
		relType := field.RelationType

		criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
			var col string
			q, col = applyRelation(q, relation, relType, field, column)
			if col == "" {
				col = column
			}
			return q.OrderExpr("? ?", bun.Safe(col), bun.Safe(dir))
		})
	}

	for _, filter := range filters {
		if filter == nil || filter.Field == "" {
			continue
		}
		field, ok := lookupField(fields, filter.Field)
		if !ok {
			continue
		}

		op := normalizeOperator(filter.Operator)
		if op == "" {
			continue
		}

		value := strings.TrimSpace(filter.Value)
		if value == "" {
			continue
		}

		column := field.Column
		relation := findOriginalNameForJoinKey(entity, filter.Field)
		relType := field.RelationType

		switch op {
		case "IN", "NOT IN":
			values := splitList(value)
			if len(values) == 0 {
				continue
			}
			criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
				var col string
				q, col = applyRelation(q, relation, relType, field, column)
				if col == "" {
					col = column
				}
				expr := fmt.Sprintf("%s IN (?)", col)
				if op == "NOT IN" {
					expr = fmt.Sprintf("%s NOT IN (?)", col)
				}
				return q.Where(expr, bun.In(values))
			})
		default:
			criteria = append(criteria, func(q *bun.SelectQuery) *bun.SelectQuery {
				var col string
				q, col = applyRelation(q, relation, relType, field, column)
				if col == "" {
					col = column
				}
				return q.Where(fmt.Sprintf("%s %s ?", col, op), value)
			})
		}
	}

	return criteria
}

func applyRelation(q *bun.SelectQuery, relation, relType string, field criteriaField, column string) (*bun.SelectQuery, string) {
	rel := strings.ToLower(strings.ReplaceAll(relType, "-", ""))
	rel = strings.ReplaceAll(rel, "_", "")
	if (rel == "manytomany" || rel == "m2m") && field.PivotTable != "" && field.SourcePivot != "" && field.TargetPivot != "" && field.TargetTable != "" {
		targetAlias := strings.ToLower(strings.ReplaceAll(field.Relation, ".", "_"))
		pivotAlias := fmt.Sprintf("%s_pivot", targetAlias)
		q = q.Join(fmt.Sprintf("JOIN %s AS %s ON %s.%s = ?TableAlias.%s", field.PivotTable, pivotAlias, pivotAlias, field.SourcePivot, field.SourceColumn))
		q = q.Join(fmt.Sprintf("JOIN %s AS %s ON %s.%s = %s.%s", field.TargetTable, targetAlias, targetAlias, field.TargetColumn, pivotAlias, field.TargetPivot))
		if strings.Contains(column, ".") {
			parts := strings.SplitN(column, ".", 2)
			column = targetAlias + "." + parts[1]
		} else {
			column = targetAlias + "." + column
		}
		return q, column
	}
	if relation != "" {
		q = q.Relation(relation)
	}
	return q, column
}

func paginationBounds(p *model.PaginationInput, returned int) (limit int, offset int) {
	if p != nil {
		if p.Limit != nil && *p.Limit > 0 {
			limit = *p.Limit
		}
		if p.Offset != nil && *p.Offset > 0 {
			offset = *p.Offset
		}
	}
	if limit <= 0 {
		limit = returned
	}
	return limit, offset
}

func buildPageInfoMeta(offset, count, limit, total int) *model.PageInfo {
	if limit < 0 {
		limit = 0
	}
	if count < 0 {
		count = 0
	}

	hasNext := offset+count < total
	if limit > 0 {
		hasNext = offset+limit < total
	}

	var startCursor, endCursor string
	if count > 0 {
		startCursor = encodeCursor(offset)
		endCursor = encodeCursor(offset + count - 1)
	}

	return &model.PageInfo{
		Total:           total,
		HasNextPage:     hasNext,
		HasPreviousPage: offset > 0,
		StartCursor:     startCursor,
		EndCursor:       endCursor,
	}
}

func encodeCursor(offset int) string {
	if offset < 0 {
		offset = 0
	}
	return base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("cursor:%d", offset)))
}

func normalizeDirection(dir *model.OrderDirection) string {
	if dir == nil {
		return "ASC"
	}
	value := strings.ToUpper(string(*dir))
	if value != "DESC" {
		return "ASC"
	}
	return value
}

func normalizeOperator(op model.FilterOperator) string {
	switch strings.ToUpper(string(op)) {
	case "EQ":
		return "="
	case "NE":
		return "<>"
	case "GT":
		return ">"
	case "LT":
		return "<"
	case "GTE":
		return ">="
	case "LTE":
		return "<="
	case "ILIKE":
		return "ILIKE"
	case "LIKE":
		return "LIKE"
	case "IN":
		return "IN"
	case "NOT_IN":
		return "NOT IN"
	default:
		return ""
	}
}

func lookupField(fields map[string]criteriaField, raw string) (criteriaField, bool) {
	if len(fields) == 0 {
		return criteriaField{}, false
	}
	key := strings.ToLower(strings.TrimSpace(raw))
	value, ok := fields[key]
	return value, ok
}

func splitList(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		val := strings.TrimSpace(part)
		if val == "" {
			continue
		}
		out = append(out, val)
	}
	return out
}

func applyInput[T any, I any](dst *T, src I) {
	if dst == nil {
		return
	}

	dv := reflect.ValueOf(dst)
	if dv.Kind() != reflect.Pointer || dv.IsNil() {
		return
	}

	sv := reflect.ValueOf(src)
	if sv.Kind() == reflect.Pointer {
		if sv.IsNil() {
			return
		}
		sv = sv.Elem()
	}

	dv = dv.Elem()

	for i := 0; i < sv.NumField(); i++ {
		sf := sv.Field(i)
		df := dv.FieldByName(sv.Type().Field(i).Name)
		if !df.IsValid() || !df.CanSet() {
			continue
		}
		if sf.Kind() == reflect.Pointer {
			if sf.IsNil() {
				continue
			}
			sf = sf.Elem()
		}
		assignField(df, sf)
	}
}

func assignField(dst, src reflect.Value) {
	switch {
	case !dst.IsValid() || !dst.CanSet():
		return
	case src.Type().AssignableTo(dst.Type()):
		dst.Set(src)
	case dst.Kind() == reflect.Pointer && src.Type().AssignableTo(dst.Type().Elem()):
		if dst.IsNil() {
			dst.Set(reflect.New(dst.Type().Elem()))
		}
		dst.Elem().Set(src)
	case src.Type().ConvertibleTo(dst.Type()):
		dst.Set(src.Convert(dst.Type()))
	case dst.Kind() == reflect.Pointer && src.Type().ConvertibleTo(dst.Type().Elem()):
		if dst.IsNil() {
			dst.Set(reflect.New(dst.Type().Elem()))
		}
		dst.Elem().Set(src.Convert(dst.Type().Elem()))
	}
}

func setID[T any](dst *T, id string) {
	dv := reflect.ValueOf(dst).Elem()
	for _, name := range []string{"ID", "Id"} {
		f := dv.FieldByName(name)
		if f.IsValid() && f.CanSet() && f.Kind() == reflect.String {
			f.SetString(id)
			return
		}
	}
}

func asUUID(id string) model.UUID { return model.UUID(id) }

func asTime(t *time.Time) *model.Time {
	if t == nil {
		return nil
	}
	val := model.Time(*t)
	return &val
}

func setUUID(dst *string, data model.UUID) {
	*dst = string(data)
}

func setUUIDPtr(dst **string, data *model.UUID) {
	if data == nil {
		*dst = nil
		return
	}
	val := string(*data)
	*dst = &val
}

func setTimePtr(dst **time.Time, data *model.Time) {
	if data == nil {
		*dst = nil
		return
	}
	val := time.Time(*data)
	*dst = &val
}

func valueString(v any) string {
	switch val := v.(type) {
	case nil:
		return ""
	case *string:
		if val == nil {
			return ""
		}
		return *val
	case fmt.Stringer:
		return val.String()
	default:
		return fmt.Sprint(val)
	}
}

func (r *Resolver) ContentService() crud.Service[model.Content] {
	if r.ContentSvc == nil {
		panic("ContentService is not configured on Resolver")
	}
	return r.ContentSvc
}

func (r *Resolver) GetContent(ctx context.Context, id string) (*model.Content, error) {
	if err := r.guard(ctx, "Content", "show"); err != nil {
		return nil, err
	}
	svc := r.ContentService()
	record, err := svc.Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListContent(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.ContentConnection, error) {
	if err := r.guard(ctx, "Content", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("Content", pagination, orderBy, filter)
	svc := r.ContentService()
	records, total, err := svc.Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	limit, offset := paginationBounds(pagination, len(records))
	result := make([]*model.Content, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	edges := make([]*model.ContentEdge, 0, len(result))
	for i := range result {
		edges = append(edges, &model.ContentEdge{
			Cursor: encodeCursor(offset + i),
			Node:   result[i],
		})
	}
	return &model.ContentConnection{
		Edges:    edges,
		PageInfo: buildPageInfoMeta(offset, len(result), limit, total),
	}, nil
}

func (r *Resolver) CreateContent(ctx context.Context, input model.CreateContentInput) (*model.Content, error) {
	if err := r.guard(ctx, "Content", "create"); err != nil {
		return nil, err
	}
	var record model.Content
	applyInput(&record, input)
	svc := r.ContentService()
	record, err := svc.Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateContent(ctx context.Context, id string, input model.UpdateContentInput) (*model.Content, error) {
	if err := r.guard(ctx, "Content", "update"); err != nil {
		return nil, err
	}
	svc := r.ContentService()
	record, err := svc.Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = svc.Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteContent(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "Content", "delete"); err != nil {
		return false, err
	}
	svc := r.ContentService()
	var record model.Content
	setID(&record, id)
	if err := svc.Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}

func (r *Resolver) MenuService() crud.Service[model.Menu] {
	if r.MenuSvc == nil {
		panic("MenuService is not configured on Resolver")
	}
	return r.MenuSvc
}

func (r *Resolver) GetMenu(ctx context.Context, id string) (*model.Menu, error) {
	if err := r.guard(ctx, "Menu", "show"); err != nil {
		return nil, err
	}
	svc := r.MenuService()
	record, err := svc.Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListMenu(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.MenuConnection, error) {
	if err := r.guard(ctx, "Menu", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("Menu", pagination, orderBy, filter)
	svc := r.MenuService()
	records, total, err := svc.Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	limit, offset := paginationBounds(pagination, len(records))
	result := make([]*model.Menu, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	edges := make([]*model.MenuEdge, 0, len(result))
	for i := range result {
		edges = append(edges, &model.MenuEdge{
			Cursor: encodeCursor(offset + i),
			Node:   result[i],
		})
	}
	return &model.MenuConnection{
		Edges:    edges,
		PageInfo: buildPageInfoMeta(offset, len(result), limit, total),
	}, nil
}

func (r *Resolver) CreateMenu(ctx context.Context, input model.CreateMenuInput) (*model.Menu, error) {
	if err := r.guard(ctx, "Menu", "create"); err != nil {
		return nil, err
	}
	var record model.Menu
	applyInput(&record, input)
	svc := r.MenuService()
	record, err := svc.Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateMenu(ctx context.Context, id string, input model.UpdateMenuInput) (*model.Menu, error) {
	if err := r.guard(ctx, "Menu", "update"); err != nil {
		return nil, err
	}
	svc := r.MenuService()
	record, err := svc.Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = svc.Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteMenu(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "Menu", "delete"); err != nil {
		return false, err
	}
	svc := r.MenuService()
	var record model.Menu
	setID(&record, id)
	if err := svc.Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}

func (r *Resolver) PageService() crud.Service[model.Page] {
	if r.PageSvc == nil {
		panic("PageService is not configured on Resolver")
	}
	return r.PageSvc
}

func (r *Resolver) GetPage(ctx context.Context, id string) (*model.Page, error) {
	if err := r.guard(ctx, "Page", "show"); err != nil {
		return nil, err
	}
	svc := r.PageService()
	record, err := svc.Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListPage(ctx context.Context, pagination *model.PaginationInput, orderBy []*model.OrderByInput, filter []*model.FilterInput) (*model.PageConnection, error) {
	if err := r.guard(ctx, "Page", "index"); err != nil {
		return nil, err
	}
	criteria := buildCriteria("Page", pagination, orderBy, filter)
	svc := r.PageService()
	records, total, err := svc.Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	limit, offset := paginationBounds(pagination, len(records))
	result := make([]*model.Page, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	edges := make([]*model.PageEdge, 0, len(result))
	for i := range result {
		edges = append(edges, &model.PageEdge{
			Cursor: encodeCursor(offset + i),
			Node:   result[i],
		})
	}
	return &model.PageConnection{
		Edges:    edges,
		PageInfo: buildPageInfoMeta(offset, len(result), limit, total),
	}, nil
}

func (r *Resolver) CreatePage(ctx context.Context, input model.CreatePageInput) (*model.Page, error) {
	if err := r.guard(ctx, "Page", "create"); err != nil {
		return nil, err
	}
	var record model.Page
	applyInput(&record, input)
	svc := r.PageService()
	record, err := svc.Create(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdatePage(ctx context.Context, id string, input model.UpdatePageInput) (*model.Page, error) {
	if err := r.guard(ctx, "Page", "update"); err != nil {
		return nil, err
	}
	svc := r.PageService()
	record, err := svc.Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	setID(&record, id)
	applyInput(&record, input)
	record, err = svc.Update(r.crudContext(ctx), record)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeletePage(ctx context.Context, id string) (bool, error) {
	if err := r.guard(ctx, "Page", "delete"); err != nil {
		return false, err
	}
	svc := r.PageService()
	var record model.Page
	setID(&record, id)
	if err := svc.Delete(r.crudContext(ctx), record); err != nil {
		return false, err
	}
	return true, nil
}
