//go:build ignore
// +build ignore

package resolvers

// Code generated by graphqlgen. DO NOT EDIT.

import (
	"context"

	"github.com/goliatone/go-crud"
	repository "github.com/goliatone/go-repository-bun"

	"graph/model"
)

type ScopeGuardFunc func(ctx context.Context, entity, action string) error
type ContextFactory func(ctx context.Context) crud.Context

func (r *Resolver) crudContext(ctx context.Context) crud.Context {
	if r.ContextFactory != nil {
		return r.ContextFactory(ctx)
	}
	return nil
}

func (r *Resolver) guard(ctx context.Context, entity, action string) error {
	if r.ScopeGuard != nil {
		if err := r.ScopeGuard(ctx, entity, action); err != nil {
			return err
		}
	}
	return nil
}

func (r *Resolver) PostService() crud.Service[model.Post] {
	if r.PostService == nil {
		panic("PostService is not configured on Resolver")
	}
	return r.PostService
}

func (r *Resolver) GetPost(ctx context.Context, id string) (*model.Post, error) {
	if err := r.guard(ctx, "Post", "show"); err != nil {
		return nil, err
	}
	record, err := r.PostService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListPost(ctx context.Context, criteria []repository.SelectCriteria) ([]*model.Post, error) {
	if err := r.guard(ctx, "Post", "index"); err != nil {
		return nil, err
	}
	records, _, err := r.PostService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Post, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreatePost(ctx context.Context, input model.Post) (*model.Post, error) {
	if err := r.guard(ctx, "Post", "create"); err != nil {
		return nil, err
	}
	record, err := r.PostService().Create(r.crudContext(ctx), input)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdatePost(ctx context.Context, input model.Post) (*model.Post, error) {
	if err := r.guard(ctx, "Post", "update"); err != nil {
		return nil, err
	}
	record, err := r.PostService().Update(r.crudContext(ctx), input)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeletePost(ctx context.Context, input model.Post) error {
	if err := r.guard(ctx, "Post", "delete"); err != nil {
		return err
	}
	if err := r.PostService().Delete(r.crudContext(ctx), input); err != nil {
		return err
	}
	return nil
}

func (r *Resolver) UserService() crud.Service[model.User] {
	if r.UserService == nil {
		panic("UserService is not configured on Resolver")
	}
	return r.UserService
}

func (r *Resolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	if err := r.guard(ctx, "User", "show"); err != nil {
		return nil, err
	}
	record, err := r.UserService().Show(r.crudContext(ctx), id, nil)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) ListUser(ctx context.Context, criteria []repository.SelectCriteria) ([]*model.User, error) {
	if err := r.guard(ctx, "User", "index"); err != nil {
		return nil, err
	}
	records, _, err := r.UserService().Index(r.crudContext(ctx), criteria)
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, 0, len(records))
	for i := range records {
		result = append(result, &records[i])
	}
	return result, nil
}

func (r *Resolver) CreateUser(ctx context.Context, input model.User) (*model.User, error) {
	if err := r.guard(ctx, "User", "create"); err != nil {
		return nil, err
	}
	record, err := r.UserService().Create(r.crudContext(ctx), input)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) UpdateUser(ctx context.Context, input model.User) (*model.User, error) {
	if err := r.guard(ctx, "User", "update"); err != nil {
		return nil, err
	}
	record, err := r.UserService().Update(r.crudContext(ctx), input)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (r *Resolver) DeleteUser(ctx context.Context, input model.User) error {
	if err := r.guard(ctx, "User", "delete"); err != nil {
		return err
	}
	if err := r.UserService().Delete(r.crudContext(ctx), input); err != nil {
		return err
	}
	return nil
}
